### ISSUE TITLE
Datadog: In a monitor with a threshold query, it fails obcurely when the query limit is not the same than the threshold

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#11106]
If the number defined in the `query` of a monitor does not match the critical threshold, Datadog API refuses to change the monitor. But the datadog terraform provider does not handle that situation and fails in a obscure way, not telling the user what the problem is.

Additionally, it leaks the datadog credentials, which I will report in a different issue.

### Terraform Version

0.7.10

### Affected Resource(s)
 - datadog

### Terraform Configuration Files

https://github.com/alphagov/paas-cf/pull/707/commits/669fa266c8e625334bade72917e2e800d742b808

### Output

```
atadog_monitor.cc_job_queue_length: Modifying...
  thresholds.critical: "10.0" => "25"
  thresholds.warning:  "7.0" => "20"
datadog_monitor.cc_job_queue_length: Still modifying... (10s elapsed)
datadog_monitor.cc_job_queue_length: Still modifying... (20s elapsed)
datadog_monitor.cc_job_queue_length: Still modifying... (30s elapsed)
datadog_monitor.cc_job_queue_length: Still modifying... (40s elapsed)
datadog_monitor.cc_job_queue_length: Still modifying... (50s elapsed)
datadog_monitor.cc_job_queue_length: Still modifying... (1m0s elapsed)
Error applying plan:

1 error(s) occurred:

* datadog_monitor.cc_job_queue_length: error updating monitor: Put https://app.datadoghq.com/api/v1/monitor/1402762?api_key=12345678901234567890234567890&application_key=12345678901234567890234567890: http: ContentLength=489 with Body length 0

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure. 
```

### Expected Behavior

Terraform should report the mismatch properly so the user can update the changes.

### Actual Behavior

It retried and gave a obscure error (see above)

It also prints the credentials of datadog :scream: 

### Steps to Reproduce

Create a monitor with a query limit different than the critical threshold, like here: https://github.com/alphagov/paas-cf/blob/8b467afbc785c337e96f355253229b34ee9d321f/terraform/datadog/cloud_controller.tf#L110

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by bshelton229** [comment]
https://github.com/zorkian/go-datadog-api/issues/91 should resolve this issue if it's merged. It has the side-effect of not exposing credentials in this particular failure case as the error is now the same as if the monitor failed on initial creation. Credentials may still be exposed with GET requests, I'm going to look at that as well.

**Comment by stack72** [comment]
Closed via upstream :)

**Comment by ojongerius** [comment]
AFAICS the problem "In a monitor with a threshold query, it fails obscurely when the query limit is not the same than the threshold" here is not closed by the merges that are referenced.

A solution for this issue would be to have a validation function that validates that the value for the `Ok` field in `ThresholdCount` does not differ from a value given in `Query` string.

For the example of a simple query like `"avg(last_15m):avg:system.disk.in_use{*} by {host,device} > 0.8`, ideally we'd fail if `Monitor.Options.Thresholds.Ok` is both set and does not match 0.8.

@stack72 I don't think a ValidateFunc is able to access config or state, is this correct? If this is the case we could do this validation while building the monitor, but it would be more messy and a lesser experience for the user.

**Comment by dcarley** [comment]
I agree, it's not fixed - there's a usability problem separate from the credentials covered in #11107.

Could the issue be reopened?
