### ISSUE TITLE
OpenStack Neutron Router Interface deletion: timeout too short

### ISSUE THREAD

**Issue by sneumann** [hashicorp/terraform#11192]
Hi,

I have a working deployment using Terraform v0.8.2 against an OpenStack installation.
When deleting, I always get 

```
* openstack_networking_router_interface_v2.main: Error deleting OpenStack Neutron Router Interface: timeout while waiting for state to become 'DELETED' (last state: 'ACTIVE', timeout: 2m0s
```

and on re-running, the deletion of the OpenStack Neutron Router Interface succeeds,
so total deletion time is probably <4min. 

I don't have a PR for @jtopjian , (who asked for it in https://github.com/hashicorp/terraform/pull/4223#issuecomment-163113311) but I think the change is required here:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_networking_router_interface_v2.go#L73

Yours,
Steffen

**Comment by jtopjian** [comment]
@sneumann Thanks for the report! #11250 should fix this for you. :)

**Comment by mcapuccini** [comment]
@jtopjian isn't 5 minutes still quite little?

**Comment by jtopjian** [comment]
@sneumann Sorry, I'm misunderstanding. I had thought that 5 minutes would be enough time since you said that the total deletion time is less than 4 minutes. Is that correct?

And absolutely - deletion and creation times are highly dependent on the OpenStack configuration. I wouldn't say that anything is wrong with your environment.

**Comment by sneumann** [comment]
Hi, I am afraid this change did not fix my issue, it timed out after 5 minutes. 
My guess would be that this particular OpenStack installation needs two kicks 
to actually delete OpenStack Neutron Router Interface. Is there anything 
I could ask to the OpenStack admins ? Or check in TF logs ? Yours, Steffen

**Comment by jtopjian** [comment]
@sneumann The delete call is repeated every 5 seconds, so I think it might just need a longer timeout. Are you able to compile the Terraform binary yourself? If so, you can increase the timeout [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_networking_router_interface_v2.go#L118) and see what the appropriate timeout is.

But if you aren't in a position to compile the binary, I can compile one for you for Linux with a timeout of 10 minutes just to see if that will help.

Either way, once confirmed, we can get it merged into master. It's entirely possible that if you need a longer timeout, there are others as well.

**Comment by Ashok2988** [comment]
Hi Jtopjian,
I am facing the similar problem, 2 minutes seem to very less in my case, could you please let me know how I can compile with the increased timeout?  atleast 5 minutes would be needed IMO. 
I am using terraform version 0.8.0

Error deleting OpenStack Neutron Router Interface: timeout while waiting for state to become 'DELETED' (last state: 'ACTIVE', timeout: 2m0s)

Thanks
Ashok

**Comment by jtopjian** [comment]
@Ashok2988 The router interface resource supports the [timeout](https://www.terraform.io/docs/configuration/resources.html#timeouts) options. Have you tried using those?

**Comment by Ashok2988** [comment]
@jtopjian  I am not using the latest version, moving to the latest would involve some work for me, do you think this can work with 0.8.0 release?

**Comment by jtopjian** [comment]
Timeouts were introduced in the 0.9.0 release, unfortunately. To fix for 0.8.0, follow the instructions on configuring a dev environment for terraform [here](https://github.com/hashicorp/terraform/blob/master/README.md#developing-terraform). When you clone the Terraform repo, you'll want to check out a 0.8.0 release. Next, edit [this](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_networking_router_interface_v2.go) file. Look for the two `stateConf` blocks. You can increase the timeouts there. Then compile Terraform per the instructions in the README.

That's a very quick / high level summary. Let me know if you run into any problems and I'd be happy to give more details. :)
