### ISSUE TITLE
terraform import appears fails to use correct provider for parts of the operation..

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#14325]
### Terraform Version
0.9.4

### Terraform Configuration Files
```hcl
provider "aws" {
  alias   = "src"
  region  = "${var.aws_src_region}"
  profile = "${var.aws_src_profile}"
}

provider "aws" {
  alias   = "dest"
  region  = "${var.aws_dest_region}"
  profile = "${var.aws_dest_profile}"
}

data "aws_caller_identity" "src" {
  provider = "aws.src"
}

resource "aws_s3_bucket" "src" {
  provider = "aws.src"
  bucket = "${var.src_bucket_name}"
  versioning {
    enabled = true
  }
  replication_configuration {
    role = "${aws_iam_role.src.arn}",
    rules = {
      prefix = ""
      status = "Enabled"
      destination {
        bucket = "${aws_s3_bucket.dest.arn}"
      }
    }
  }
}

resource "aws_s3_bucket" "dest" {
  provider = "aws.dest"
  bucket = "${var.dest_bucket_name}"
  versioning {
    enabled = true
  }
  policy = <<EOF
{
   "Version":"2008-10-17",
   "Id":"",
   "Statement":[
      {
         "Effect":"Allow",
         "Principal":{
            "AWS":"arn:aws:iam::${data.aws_caller_identity.src.account_id}:root"
         },
         "Action":["s3:ReplicateObject", "s3:ReplicateDelete"],
         "Resource":"arn:aws:s3:::${var.dest_bucket_name}/*"
      }
   ]
}
EOF
}
```

### Expected Behavior
s3 bucket should have been imported to the state file.

### Actual Behavior
the output implies that the aws s3 bucket resource was located and queried -  but that a subsequent (internal to the command) "Refreshing state" failed due to improper aws credentials.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```
terraform import \
>     -provider aws.src \
>     -var aws_src_profile=src -var aws_src_region=us-east-1 -var src_bucket_name=src \
>     -var aws_dest_profile=dest -var aws_dest_region=us-west-1 -var dest_bucket_name=dest \
>     -var application=app \
>     aws_s3_bucket.src src
```

### Important Factoids
The terraform source uses two aws providers, each with an alias.  The `terraform import` command appears to use that, correctly, for the *import* step, but then forget to use them for the *refresh* step.  Another oddity is that the command prompts for the default region as it starts up, but also continues to run (making the output from the command interleave the prompt/answer and further output.)  Entering a region, or just pressing ENTER, does not make any difference and the command still fails.  It is telling that if, in addition to the command as it stands, I prefix it with some environment variables: `AWS_DEFAULT_REGION="us-east-1" AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx` for the (in this case) `src` account - the command executes correctly.  Here is the output from the import command above:

```
*provider.aws.region*
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: *aws_s3_bucket.src: Importing from ID "src"...*
aws_s3_bucket.src: Import complete!
  Imported aws_s3_bucket (ID: src
*aws_s3_bucket.src: Refreshing state... (ID: src)*

*I PRESSED ENTER*
Error importing: 1 error(s) occurred:

* provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider```

**Comment by automaticgiant** [comment]
yeah - i was trying to use a common infra data module that i set up with an environment variable for input that keyed a map with things including profile, but i couldn't get the refresh step to respect the provider.aws.profile i supplied using that modules output. so there's definitely a disconnect between refresh and declared providers.

**Comment by tPl0ch** [comment]
Any progress here? I am hitting the same issue here when trying to import a KMS key.

**Comment by nshenry03** [comment]
I also had this issue w/ v0.10.2 and v0.10.6  while importing aws users.

```bash
terraform import --provider=aws.awssecurityad aws_iam_user.jdoe_awssecurityad jdoe@example.com
```

worked around it w/ 
```bash
  AWS_ACCESS_KEY_ID='xxx' AWS_SECRET_ACCESS_KEY='xxx' terraform import --provider=aws.awssecurityad aws_iam_user.jdoe_awssecurityad jdoe@example.com
```

**Comment by jbardin** [comment]
This is fixed in master, and will be in the 0.11 release.

**Comment by sudoforge** [comment]
Unless I'm doing something wrong, this does not be appeared to be resolved for the version matrix:

```
Terraform v0.11.7
+ provider.google v1.10.0
```

My use case may be nonstandard. I am creating Terraform resources for a Google Cloud Platform account which has four total projects:

* a-prod
* a-dev
* b-prod
* b-dev

Each `*-dev` project will have the exact same configuration, and each `*-prod` project will have the exact same configuration. To accomplish this in a simplified manner, I have created the following structure (we'll look at the `-*dev` environment specifically):

```
/infra/gcp/dev
|
| - modules/
|  |- iam/
|  |  |- roles/
|  |  |  |- foo/
|  |  |  |  |- main.tf
|  |
|  |- main.tf
```

In `/main.tf` at the root level, I am defining **two** provider blocks, and sourcing the `iam/roles/foo` module twice, once with each provider. Both providers are passed into the `foo` module when it is sourced (in `/main.tf`), and `foo` defines two resources, using one provider in each.

This accomplishes my goal of defining the "thing" (a custom role, in this case) once, and using Terraform to manage the "thing" in two projects simultaneously.

**The problem arises** when attempting to import existing resources using this structure. For clarity, a resource defined in the `foo` module for the GCP project `a-dev` should be imported (according to documentation), like so (from the root directory):

```
terraform import \
    module.iam_role_dev_foo.google_project_iam_custom_role.a_dev_iam_role_foo \
    projects/a-dev/roles/foo
```

The above command fails to work, because there is no default `google` provider block configured. Fortunately, the provider can be specified like so (where `a_dev` is the provider's alias:

```
terraform import \
    -provider="a_dev" \
    module.iam_role_dev_foo.google_project_iam_custom_role.a_iam_role_dev_foo \
    projects/a-dev/roles/foo
```

This successfully imports the resource, but fails to refresh the state:

```
module.iam_role_dev_foo.google_project_iam_custom_role.a_dev_iam_role_foo: Importing from ID "projects/a-dev/roles/foo"...
module.iam_role_dev_foo.google_project_iam_custom_role.a_dev_iam_role_foo: Import complete!

  Imported google_project_iam_custom_role (ID: projects/a-dev/roles/foo)
module.iam_role_dev_foo.google_project_iam_custom_role.a_dev_iam_role_foo: Refreshing state... (ID: projects/a-dev/roles/foo)

Error: provider.google: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

I believe my structure is following the best practices for environment management, at least based on the documentation I've read. In my opinion, if a provider is explicitly defined using the `-provider` flag, then `terraform import` should ensure that the defined provider is used for _all_ operations.

_Note to other users who may stumble upon this with the same issue: I worked around this by generating default application credentials for my IAM user via `google auth application-default login`. I then removed the `credentials.json` file and revoked access to the Auth application in the [App Permissions][0] page._

[0]: https://myaccount.google.com/permissions "Apps with permissions to your Google account"

**Comment by pawelkopka** [comment]
We have same problem with v0.11.7
`resource "aws_eip" "GW_1_Pseudopolis_0" {
    "vpc" =  true
    "provider" =  "aws.eu-west-3"
}
provider aws {
         "access_key" = "xxx",
          "alias" = "eu-west-3",
          "region" = "eu-west-3",
          "secret_key" = "xxx"
}`

Get:
`11:16 $ terraform import -provider=aws.eu-west-3 aws_eip.GW_1_Pseudopolis_0 35.180.2.218
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: aws_eip.GW_1_Pseudopolis_0: Importing from ID "35.180.2.218"...
aws_eip.GW_1_Pseudopolis_0: Import complete!
  Imported aws_eip (ID: 35.180.2.218)
aws_eip.GW_1_Pseudopolis_0: Refreshing state... (ID: 35.180.2.218)
Error: provider.aws: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: c8832746-5369-11e8-be09-bbacb2d829f
`

When we remove alias:
`resource "aws_eip" "GW_1_Pseudopolis_0" {
    "vpc" =  true
}
provider aws {
         "access_key" = "xxx",
          "region" = "eu-west-3",
          "secret_key" = "xxx"
}`
Get:
`11:18 $ terraform import  aws_eip.GW_1_Pseudopolis_0 35.180.2.218
aws_eip.GW_1_Pseudopolis_0: Importing from ID "35.180.2.218"...
aws_eip.GW_1_Pseudopolis_0: Import complete!
  Imported aws_eip (ID: 35.180.2.218)
aws_eip.GW_1_Pseudopolis_0: Refreshing state... (ID: 35.180.2.218)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
`

Version:
`11:18 $ terraform version
Terraform v0.11.7
+ provider.aws v1.10.0
`

**Comment by jasonmcintosh** [comment]
Want to second this issue.  Using 0.11.7

Terraform import first stage works fine.  Finds the resource.  Second stage on the refresh ignores the provider block it seems.  This hits us on assumed roles:
```
provider "aws" {
  assume_role {
    role_arn     = "arn:aws:iam::12341235123:role/admin"
  }
}
```
We do this as we run with credentials from a master account 55555555.  The permissions work let us import, then refresh fails and doesn't seem to use the above role assumption :(

**Comment by Alberts00** [comment]
Hello @jbardin, is there any chance this could be reopened? This is definitely still an issue in v0.11.13 and most likely also in 0.12.

**Comment by jbardin** [comment]
Hi @Alberts00,

I believe you are looking for #18257 and/or #13018 if you want to follow the open issues. If those don't cover your use case, please file a new issue with the configuration and steps to reproduce it.
