### ISSUE TITLE
[Suggestion] Round() function

### ISSUE THREAD

**Issue by DWSR** [hashicorp/terraform#16251]
We have `ceil()` and `floor()` but no `round()`. Methinks this is an oversight.

**Comment by apparentlymart** [comment]
Hi @DWSR! Thanks for this suggestion.

Do you have a particular use-case in mind for a hypothetical `round` function?

**Comment by beatcracker** [comment]
> Do you have a particular use-case in mind for a hypothetical round function?

I'm currently doing some math on `k8s` allocatable resources and `0.6 - 0.2` gives me `0.39999999999999997`. This will probably be fixed in ` 0.12` with decimals (#14967), but there are still plenty of reasons for being able to round values.

**Comment by apparentlymart** [comment]
The reason I'd requested use-cases is because that both helps prioritize development _and_ helps create some requirements for the feature. There's a few different ways to implement "rounding" (bankers round, closest-integer round, etc) and so knowing specific use-cases will help to decide whether one specific rounding approach is what we need, whether we need to provide more than one, etc.

For this `0.6 - 0.2` bug it probably will indeed be fixed in 0.12, but that serves to illustrate another possible variable in how we might define this: I assume for that you'd want to specify the number of decimal places and/or the number of significant figures to round to.

We currently have support for _display-oriented_ rounding in the `format` function using modifiers on the `%f`, `%g` etc verbs, and since Terraform can auto-convert from string back to numeric when needed, perhaps that's sufficient to meet use-cases.

**Comment by beatcracker** [comment]
> We currently have support for display-oriented rounding in the format function

Missed that one: `format("%.2f", (0.6 - 0.2))` will do for now. Thanks!

> There's a few different ways to implement "rounding" (bankers round, closest-integer round, etc) and so knowing specific use-cases will help to decide whether one specific rounding approach is what we need, whether we need to provide more than one, etc.

I can't come up with more use-cases, assuming that the floats issue will be gone in `0.12`. But for the sake of the argument, here is the proposal.

Since it'll probably will be (if ever) implemented in `0.12.x`, I was imagining something like this:
```
round(decimal, mode)
```

where mode is akin to [MidpointRounding Enum](https://docs.microsoft.com/en-us/dotnet/api/system.midpointrounding):

| Mode | Description |
|--|--|
| AwayFromZero | When a number is halfway between two others, it is rounded toward the nearest number that is away from zero.  |
| ToEven | When a number is halfway between two others, it is rounded toward the nearest even number (banker's rounding). |

> I assume for that you'd want to specify the number of decimal places and/or the number of significant figures to round to

Since we've got this wonderful `format` function, we can use it if we need output with controlled precision. So there is no need to implement it in `round`.

```
format("%.2f", round(decimal, mode))
```

**Comment by apparentlymart** [comment]
Thanks for the proposal, @beatcracker! Unfortunately that's still not actually a _use case_, and so we can't really evaluate the proposal because there are no criteria to evaluate it against: we don't know what problem we're trying to solve.

We have the `floor` and `ceil` functions because historically people were using them for bucketing behaviors, IP address calculations, etc where it was important to control the rounding direction for consistent results. It's not so clear to me why an infrastructure provisioning tool needs a banker's round, and each new thing we add is a maintenance burden so it's important to make sure it meets a specific need.

The `format` function is apparently already implementing the "to even" (banker's round) behavior:

```
> format("%.0f", 0.5)
0
> format("%.0f", 1.5)
2
> format("%.0f", 2.5)
2
> format("%.0f", 3.5)
4
> format("%.0f", 4.5)
4
```

...so I think at this point the questions to answer here are twofold:

1. Is "bankers round" a common enough operation in Terraform to deserve a separate function for it, or can we live with just using `format` for the rare situation where it comes up?
2. Is the bankers round sufficient or are there use-cases where "away from zero" is needed instead?

The answers to those questions must come from real-world scenarios where there's an actual problem to be solved. My instincts are telling me that between `floor`, `ceil`, and `format` we've already got more than we really need in this regard, but I'll still leave this issue open for now in case someone can share a use-case I'm not thinking of.

**Comment by lindhe** [comment]
I believe I have a usecase for a `round()` function.

I have a number of disk partitions and want to create a disk that's at least as large as the sum of all partitions. I'm not sure if it's only for aesthetics or because there's a technical benefit to it, but I'd much rather create a 100 GB disk than a 96.3 GB disk. Thus, I'd like to round the sum up to the closest 10.

**Comment by apparentlymart** [comment]
Hi @lindhe! Thanks for sharing the use-case anyway, since it's useful to have it documented here. (Terraform and Packer have significant overlap in their use-cases.)

Since your particular requirement is "at least as large", that seems like you'd always want to round _up_, rather than using a round-to-nearest approach like banker's round. We already have [the `ceil` function](https://developer.hashicorp.com/terraform/language/functions/ceil) which implements rounding up to the nearest whole number, although of course `ceil(96.3)` would produce `97`, not `100`.

In the past I've met use-cases like this by combining `ceil` with division and multiplication. For example: `ceil(96.3 / 10) * 10` produces `100`.

The `ceil` function actually belongs to an upstream library that Terraform and Packer both depend on, and so [Packer's `ceil` function](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/functions/numeric/ceil) should be the same as Terraform's, and thus the example I shared above should work the same in Packer too.

**Comment by crw** [comment]
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!

**Comment by ryan-dyer-sp** [comment]
Another use case involving AWS Network FW Rule Groups.  As part of their declaration you have to define a [capacity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_rule_group#capacity).  We utilize a data source from github to pull in their list of IPs for whitelist purposes.  This list is variable and typically slowly increases over time.  But modifying capacity is not possible once created.  And when planning the provider doesnt bother to check if your new list of rules will exceed the capacity of the rule group.  So its not until apply time that you learn you need to expand capacity.

So if we had a round function we could calculate the exact capacity required based on all the rules we are about to create and then round up to closest X (50 for us for this use case).  Then we would be able to see that the new data source will blow out the existing capacity in the plan, but also provide a buffer for future rules to be added wo/ the need to recreate the rule group.  Recreation of the rule group results in an outage so its not something we want to do everytime github adds/removes an IP (if we were to set capacity to exactly whats needed).  

Thanks!
