### ISSUE TITLE
Crash when following "Dependencies" guide

### ISSUE THREAD

**Issue by LukeHoersten** [hashicorp/terraform#1739]
https://www.terraform.io/intro/getting-started/dependencies.html

When adding the elastic IP, crashed on applying. The elastic IP does get allocated and associated with the instance but the crash causes the terraform state to not record that and then it's out of sync.

Config:
```
resource "aws_instance" "test" {
    ami = "ami-408c7f28"
    tags {
        Name = "terraform-01"
    }
    instance_type = "t1.micro"
}

resource "aws_eip" "ip" {
    instance = "${aws_instance.test.id}"
}
```

Crash log:
https://gist.github.com/LukeHoersten/ea968608246e8167c538

**Comment by catsby** [comment]
Thanks @LukeHoersten , I'll take a look

**Comment by catsby** [comment]
Hey @LukeHoersten can you reliably reproduce this? I've tried a time or two, including different regions, and I can't reproduce this.

**Comment by LukeHoersten** [comment]
Yes I can. Any trace or something I can get to help?

**Comment by LukeHoersten** [comment]
I did a `terraform refresh; terraform destroy`, cleaned out all the unallocated elastic IPs all the failed `apply` attempts made, downloaded new fresh osx-64 binaries and tried again with the same crash on trying to allocated the elastic IP to the EC2 instance. 100% reproducible. I think my exact version is in the crash log so you can be sure of that.

**Comment by mitchellh** [comment]
AH! The reason that this isn't reproducible by us @clint is that it was fixed in master, and also its a ec2-classic thing. This was fixed if you git blame the line that the panic happens on, its gone. :)

**Comment by LukeHoersten** [comment]
Great thanks guys. When will this make its way into the released binary?

**Comment by mitchellh** [comment]
Within a couple weeks, most likely next

**Comment by LukeHoersten** [comment]
Has a new release been made yet? I'm still having the issue with the binaries available online (v. 0.5.0).

**Comment by phinze** [comment]
Hi Luke,

Just tested the v0.5.0 release and it seems to be working okay:

https://gist.github.com/phinze/6b368e43c54cc85da5e1

If you're still getting a reliable crash on v0.5.0, you can file a GitHub
issue [1] with the steps to reproduce and we'll take a closer look for you.

Paul

[1] https://github.com/hashicorp/terraform/issues/new

**Comment by LukeHoersten** [comment]
I'm sorry I'm still on 0.4.2. I upgraded incorrectly. My mistake. I'll file an issue if needed but I'm sure it's fixed. Thanks guys.

**Comment by catsby** [comment]
Thanks for the follow up @LukeHoersten , let us know if you still run into this.
