### ISSUE TITLE
v0.12.0-alpha2: ssh: handshake failed for file-provisioner

### ISSUE THREAD

**Issue by stephan2012** [hashicorp/terraform#19387]
### Terraform Version

```
Terraform v0.12.0-alpha2
+ provider.aws v1.40.0-6-gb23683732
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "linux_node" {
  count             = "${var.instances}"
  ami               = "ami-0c0d066cb8b155cbe"
  instance_type     = "${var.ec2_instance}"
  key_name          = "${var.ssh_key_name}"
  availability_zone = "${var.ec2_az}"
  tags              = "${merge(var.tags, map("index", count.index + 1), map("Name", format("%s-%d", var.name_prefix != "" ? var.name_prefix : "vwg", var.instance_offset + count.index + 1)) )}"

  # Connect eth0 only. Otherwise, all interfaces are configured by
  # DHCP and a random default route will be choosen rendering the
  # system inaccessible
  network_interface {
    network_interface_id = "${aws_network_interface.management_interface.*.id[count.index]}"
    device_index = 0
  }

  connection {
    type = "ssh"
    user = "admin"
    private_key = file("/home/au/.ssh/id_rsa_aws")
  }

  provisioner "file" {
    source = "${path.module}/conf/interfaces"
    destination = "/tmp/interfaces"
  }

  provisioner "file" {
    source = "${path.module}/conf/eth0"
    destination = "/tmp/eth0"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo ifdown -X eth0 -a",
      "sudo chown root:root /tmp/interfaces /tmp/eth*",
      "sudo chmod 0644 /tmp/interfaces /tmp/eth*",
      "sudo mv /tmp/interfaces /etc/network/interfaces",
      "sudo mv /tmp/eth* /etc/network/interfaces.d/"
    ]
  }

}
```

### Debug Output

```
2018-11-16T20:39:29.134+0100 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/11/16 20:39:29 [DEBUG] connecting to TCP connection for SSH
2018-11-16T20:39:29.134+0100 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/11/16 20:39:29 [DEBUG] handshaking with SSH
2018-11-16T20:39:29.153+0100 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/11/16 20:39:29 [WARN] ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
2018-11-16T20:39:29.153+0100 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/11/16 20:39:29 [WARN] retryable error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
2018-11-16T20:39:29.153+0100 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/11/16 20:39:29 [INFO] sleeping for 4s
```

### Expected Behavior

SSH connect should succeed as it did with Terraform 0.11.10.

### Actual Behavior

File provisioner cannot connect to the host.

### Steps to Reproduce

Setup an `aws_instance` and use the file provisioner.

### Additional Context

Worked flawlessly in 0.11.10.

**Comment by stephan2012** [comment]
By the way,

```hcl
private_key = "${file("/home/au/.ssh/id_rsa_aws")}"
```

(as used in 0.11) does not change the behavior.

**Comment by apparentlymart** [comment]
Hi @stephan2012! Sorry for this weird behavior and thanks for reporting it.

I'm not sure exactly what's going on here, but it's possible that this is the result of an intentional change in Terraform 0.12 which we neglected to cover in the partial draft upgrade notes: arguments in the `connection` block are no longer set automatically by plucking certain attributes out of the corresponding instance.

We could verify this by re-running your configuration here with an explicit `host` setting:

```hcl
  connection {
    type = "ssh"
    host = self.private_ip # or public_ip, depending on what's best for your environment
    user = "admin"
    private_key = file("/home/au/.ssh/id_rsa_aws")
  }
```

The specific error you got here doesn't seem like a good fit for this explanation, but I wonder if there's a subtle bug here where Terraform is failing to handle properly the case where `host` is not set. (It should be considered to be a required argument now.)

The reason for this change is that in practice this automatic population wasn't used in many resource types aside from `aws_instance` because there are usually several possible addresses or hostnames and Terraform has no way to know which one is best so it must just make an arbitrary decision. That then leaves implicit something that ought to be explicit, creating confusion for future readers of the configuration. Since the handling of the `connection` block had to be rewritten for 0.12 anyway, and this feature was both rarely used and tended to cause confusion, we elected to simplify the model by removing what was essentially a special case here.

We are planning to have the configuration upgrade tool take care of this automatically by adding in an additional `host` argument to the `connection` block for any `aws_instance` resource that doesn't already have one, selecting the same value that the old automatic behavior would've selected.

**Comment by stephan2012** [comment]
@apparentlymart: Thanks for your feedback. I can confirm that explicitly setting `host` resolves the SSH connectivity issue. And your reasoning makes sense as I've hit issues already when instances have more than one network interfaces.

**Comment by apparentlymart** [comment]
Great, thanks for confirming!

In that case I think this issue represents two related work items:

1. Terraform is not validating that `host` is set. It should behave as a required attribute in v0.12, ideally also with a helpful error message that suggests how to upgrade configurations written for v0.11 and prior.
2. The upgrade tool should fix this automatically. This was already on my private list of things to do for the upgrade tool, but it's nice to have it written down here on GitHub too.

We'll leave this issue open until both of these things are resolved in the `master` branch.

Thanks again for reporting this!

**Comment by jbardin** [comment]
The host field is now required in a connection block via #19707, but I'll leave this open until the upgrade tool is updated as well.

**Comment by apparentlymart** [comment]
As part of #20438 the upgrade tool will now fill in the `host` argument for any resource type it knows about that had automatic connection info populating in Terraform 0.11 and earlier. It can't automatically fix any third-party providers distributed outside of the HashiCorp plugin repository, but I think that's the best we can reasonably do for now. There'll be a note in the upgrade guide about this for those who need to update their configurations manually in third-party resource types.

**Comment by dbadrak** [comment]
I just ran into this same problem, but on 0.11.13.  This worked earlier this week, though probably on an older version of the provider (I don't have the provider version at that time).

```
% terraform version
Terraform v0.11.13
+ provider.aws v2.6.0
+ provider.dns v2.0.0
+ provider.external v1.1.1
+ provider.null v2.1.1
+ provider.postgresql v0.2.1
+ provider.random v2.1.1
+ provider.template v2.1.1
```

I updated my module using the file provisioner to use the host argument.

```
  provisioner "file" {
    source      = "./local/edl-provision"
    destination = "/tmp"
    on_failure  = "fail"

    connection {
      type        = "ssh"
      user        = "ec2-user"
      host        = "${self.private_ip}"
      private_key = "${file("setup/inf-keypair")}"
    }
  }
```

**Comment by dbadrak** [comment]
I still can't determine what provider I had (I had cleaned up my .terraform directories and done a re-init), but I deployed an instance using the same module I wrote without the host argument on 4-9, and making no changes to it (or any other apsects of it) it failed on a repeat on 4-11.

**Comment by AlexsanderAR** [comment]
Same issue, but with vmware (there is not private_ip on vmware provider).
Any idea?
