### ISSUE TITLE
Crash on "terraform apply" with windows was_instance

### ISSUE THREAD

**Issue by nikkiki** [hashicorp/terraform#19982]
### Terraform Version
```
$ terraform -v
Terraform v0.11.11
+ provider.aws v1.30.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
```

### Terraform Configuration Files
```hcl
resource "aws_instance" "windows_agent" {
  ami = "${lookup(var.windows_amis, var.region)}"
  instance_type = "t2.micro"
  get_password_data = true
  subnet_id = "${aws_subnet.main.id}"
  associate_public_ip_address = true
  key_name = "${var.username}"

  connection {
    type = "winrm"
    user = "Administrator"
    password = "${rsadecrypt(self.password_data,local.private_key)}"
    agent_identity = "${var.username}"
    private_key = "${local.private_key}"
  }

  depends_on = ["aws_instance.backend", "data.external.windows_executable"]
  timeouts {
     create = "10m"
     delete = "10m"
  }
  vpc_security_group_ids = ["${aws_security_group._staging.id}"]
}
```

### Debug Output
[debug.log](https://github.com/hashicorp/terraform/files/2751432/debug.log)

### Crash Output
[crash.log](https://github.com/hashicorp/terraform/files/2751434/crash.log)

### Expected Behavior
Windows AWS Instance is deployed.

### Actual Behavior
Crash.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
Ubuntu instances spin up fine.. maybe something wrong with my windows config?

### References
N/A

**Comment by apparentlymart** [comment]
Sorry for this crash, @nikkiki.

Here is the stack trace portion of the log:

```
2019-01-11T15:20:49.356-0800 [DEBUG] plugin.terraform: panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2019-01-11T15:20:49.356-0800 [DEBUG] plugin.terraform: 
2019-01-11T15:20:49.356-0800 [DEBUG] plugin.terraform: goroutine 113 [running]:
2019-01-11T15:20:49.356-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc00034ab60, 0xc00089c630, 0x1, 0x1, 0xc00089c612, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-01-11T15:20:49.356-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:509 +0x449
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc00034ab60, 0x3be4ab8, 0x7, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:480 +0x122
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc00034ab60, 0x3be4ab8, 0x7, 0xc00089c501, 0x0, 0x0, 0x0, 0x0)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:457 +0x97
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc00097c840, 0x3be4ab8, 0x7, 0xc0003d0a50, 0xc000557630, 0x3e9a200, 0xc00034ab60, 0xc0000db600, 0x0, 0x0)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/schema.go:1158 +0xa0
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc00097c840, 0x3be4ab8, 0x7, 0xc0003d0a50, 0xc0008b4180, 0x3e9a200, 0xc00034ab60, 0xc0003c2600, 0x0, 0x0)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/schema.go:774 +0x436
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc00097c840, 0x0, 0xc00021c5a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/schema.go:424 +0x206
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/helper/schema.(*Provisioner).Apply(0xc00098a870, 0x3e80fc0, 0xc000516010, 0xc0006fe000, 0xc00021c5a0, 0x0, 0x7700d80)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/helper/schema/provisioner.go:163 +0x29b
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: github.com/hashicorp/terraform/plugin.(*ResourceProvisionerServer).Apply(0xc000992500, 0xc0008943a0, 0xc000498258, 0x0, 0x0)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/private/tmp/terraform-20181217-8044-ytqj2j/terraform-0.11.11/src/github.com/hashicorp/terraform/plugin/resource_provisioner.go:142 +0x168
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: reflect.Value.call(0xc0002fcae0, 0xc000516300, 0x13, 0x3be09f0, 0x4, 0xc0009b9f18, 0x3, 0x3, 0xc000210b00, 0xc00000c8f0, ...)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.11.4/libexec/src/reflect/value.go:447 +0x454
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: reflect.Value.Call(0xc0002fcae0, 0xc000516300, 0x13, 0xc000067f18, 0x3, 0x3, 0x0, 0xc000067f38, 0x11d6217)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.11.4/libexec/src/reflect/value.go:308 +0xa4
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: net/rpc.(*service).call(0xc000506a40, 0xc00098a9b0, 0xc00097ef00, 0xc00097ef10, 0xc000304600, 0xc0009925a0, 0x30ab8c0, 0xc0008943a0, 0x16, 0x30ab900, ...)
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.11.4/libexec/src/net/rpc/server.go:384 +0x14e
2019-01-11T15:20:49.357-0800 [DEBUG] plugin.terraform: created by net/rpc.(*Server).ServeCodec
2019-01-11T15:20:49.358-0800 [DEBUG] plugin.terraform: 	/usr/local/Cellar/go/1.11.4/libexec/src/net/rpc/server.go:481 +0x47e
```

This doesn't seem like a Windows-specific problem. I think we've seen this before in situations where a string is expected but the configuration contains a list; there is some missing validation in the 0.11 releases that has been fixed for the forthcoming 0.12.0 release.

The mentions of `Provisioner` in the stack trace suggest that the problem originates in one of the `provisioner` blocks here. I think it's the following line:

```hcl
    content = "${data.template_file.agent_config_windows.*.rendered}"
```

The splat operator here returns a list of strings. It may work to instead write `data.template_file.agent_config_windows.rendered` here to get the value of the single rendered template, if that data source doesn't have `count` set.

The validation for this gets "missed" in v0.11 because Terraform doesn't yet know the value of `.rendered` at validation time. In the forthcoming Terraform v0.12.0 release this is fixed by allowing Terraform to determine that `.rendered` is a string, and thus that `.*.rendered` is a string, even though the value of `rendered` isn't known yet. Therefore once v0.12.0 is out this problem should produce a better error message saying that a string is required for that argument.

**Comment by nikkiki** [comment]
@apparentlymart thanks so much for the quick triage! You're right, that data source did not have a count set, and therefore removing the splat operator resolved the crash. Could you point me in the right direction for where I might find the solution to this error: `aws_instance.windows_agent: timeout - last error: unknown error Post http://54.185.255.125:5985/wsman: dial tcp 54.185.255.125:5985: i/o timeout`. I suspect there is something else misconfigured, but I am having little luck finding similar issues or cookie cutter windows provisioner examples.

**Comment by apparentlymart** [comment]
Hi @nikkiki,

I'm not too familiar with `winrm`, to be honest, but that does seem like a WinRM connection error since port 5985 is the WS-Management port. Could it be that the security group for this instance doesn't permit incoming connections on port 5985?

**Comment by nikkiki** [comment]
@apparentlymart I'm not too familiar with it either 😆 but yes, the ports are open and still the same error 😞. Is there perhaps documentation or an example of a cookie cutter windows config for terraform? I haven't found one that's been successful yet.

**Comment by nikkiki** [comment]
I appreciate all the help thus far! I'm going to close this out, since the crash has been resolved by your suggestion.
