### ISSUE TITLE
data terraform_remote_state: "config.0.endpoints must be a single value, not a list"

### ISSUE THREAD

**Issue by acidwars** [hashicorp/terraform#20066]
### Terraform Version

```
v0.11.11
```

### Terraform Configuration Files

```hcl
 terraform {
   backend "etcdv3" {
     endpoints = ["etcd-1:2379"]
     lock      = true
     prefix    = "terraform-state/application/"
   }
 }
 data "terraform_remote_state" "infrastructure" {
     backend = "etcdv3"
     config {
         endpoints = ["etcd-1:2379"]
         prefix    = "terraform-state/infrastructure/"
         lock      = true
     }
 }

```

### Debug Output

data.terraform_remote_state.infrastructure - *terraform.NodeValidatableResourceInstance
2019/01/21 15:35:35 [TRACE] dag/walk: added new vertex: "data.terraform_remote_state.infrastructure"
2019/01/21 15:35:35 [TRACE] dag/walk: walking "data.terraform_remote_state.infrastructure"
2019/01/21 15:35:35 [TRACE] vertex 'root.data.terraform_remote_state.infrastructure': walking
2019/01/21 15:35:35 [TRACE] vertex 'root.data.terraform_remote_state.infrastructure': evaluating
2019/01/21 15:35:35 [TRACE] [walkValidate] Entering eval tree: data.terraform_remote_state.infrastructure
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalSequence
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalValidateResourceSelfRef
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalGetProvider
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalInterpolate
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalValidateResource
2019/01/21 15:35:35 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [config.0.endpoints must be a single value, not a list]
2019/01/21 15:35:35 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [config.0.endpoints must be a single value, not a list]
2019/01/21 15:35:35 [TRACE] [walkValidate] Exiting eval tree: data.terraform_remote_state.infrastructure
2019/01/21 15:35:35 [TRACE] dag/walk: walking "meta.count-boundary (count boundary fixup)"
2019/01/21 15:35:35 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': walking
2019/01/21 15:35:35 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': evaluating
2019/01/21 15:35:35 [TRACE] [walkValidate] Entering eval tree: meta.count-boundary (count boundary fixup)
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundaryGlobal
2019/01/21 15:35:35 [TRACE] [walkValidate] Exiting eval tree: meta.count-boundary (count boundary fixup)
2019/01/21 15:35:35 [TRACE] dag/walk: walking "provider.terraform (close)"
2019/01/21 15:35:35 [TRACE] vertex 'root.provider.terraform (close)': walking
2019/01/21 15:35:35 [TRACE] vertex 'root.provider.terraform (close)': evaluating
2019/01/21 15:35:35 [TRACE] [walkValidate] Entering eval tree: provider.terraform (close)
2019/01/21 15:35:35 [TRACE] root: eval: *terraform.EvalCloseProvider
2019/01/21 15:35:35 [TRACE] [walkValidate] Exiting eval tree: provider.terraform (close)
2019/01/21 15:35:35 [TRACE] dag/walk: walking "root"
2019/01/21 15:35:35 [TRACE] vertex 'root.root': walking

### Expected Behavior

The data resource should be accepted
### Actual Behavior

Terraform complains "config.0.endpoints must be a single value, not a list"
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by mildwonkey** [comment]
According to the [etcd backend docs](https://www.terraform.io/docs/backends/types/etcd.html#endpoints), endpoints should be a space-separated string, not a list:
```hcl
 data "terraform_remote_state" "infrastructure" {
     backend = "etcdv3"
     config {
         endpoints = "etcd-1:2379"
         prefix    = "terraform-state/infrastructure/"
         lock      = true
     }
 }
```

**Comment by remoe** [comment]
@mildwonkey , sorry this doesn't work. This gives the following error:

```* endpoints: should be a list```

**Comment by mildwonkey** [comment]
I am sorry about that, @remoe !

**Comment by apparentlymart** [comment]
I think probably the most accurate characterization of this is as a design flaw in `terraform_remote_state`, since as implemented in 0.11 it only supports string-typed arguments, but the underlying provider is expecting a list here.

The good news is that this is already fixed in the master branch for the forthcoming Terraform v0.12.0 release because this data source has been rewritten to make full use of the new type system we've introduced for the configuration language. To be specific, it retrieves the expected schema from the selected backend and uses that to validate the contents of the `config` map, rather than just treating it as a map of strings.

Since `config` is a map argument rather than a nested block (its valid keys are determined dynamically at runtime rather than hard-coded into the provider), Terraform 0.12 requires assigning its value with the equals sign, resulting in this minimal change from what you wrote in your example:

```hcl
 data "terraform_remote_state" "infrastructure" {
     backend = "etcdv3"
     config = {
         endpoints = ["etcd-1:2379"]
         prefix    = "terraform-state/infrastructure/"
         lock      = true
     }
 }
```

Since this is already fixed in master, I'm going to close this out. This was fixed long enough ago that I believe the fix should be in the alpha4 release if you'd like to test (but please don't use it with "real" infrastructure), though alpha4 is quite old at this point and numerous other bugs have been fixed in the mean time. Beta1 will be coming soon with this fix and many more, as we get closer to the final release.

**Comment by remoe** [comment]
@apparentlymart , any change to fix this on 0.11.12 as well? Because it is not possible to read TF states from ETCDV3 backend with "data.terraform_remote_state".

**Comment by sashanka-kandala** [comment]
I am still getting this error "config.0.endpoints must be a single value, not a list".
Terraform v0.11.14
```
data "terraform_remote_state" "abc" {
  backend = "etcdv3"
  config = {
  endpoints = ["https://abc:port"]
  prefix    = "test/"
  lock = "true"
  }
```
