### ISSUE TITLE
"Error: Provider configuration not present" when aliased provider is used

### ISSUE THREAD

**Issue by ephur** [hashicorp/terraform#21416]
### Terraform Version
```
Terraform v0.12.0
```

With terraform version 0.11.10, the files below work as expected.

### Terraform Configuration Files

initially the `providers` section in the config below was absent, but it was added to try and troubleshoot the issue. The same results happen if it is absent or present.
```hcl
provider "aws" {
  region = "us-west-2"
  alias  = "env"
}

provider "aws" {
  region = "us-west-2"
}

provider "google" {
  credentials = "${file("gcp.json")}"
  region      = "us-central1"
  project     = "orv5-236500"
}

module "network" {
  source = "../../../../terraform-modules/gcp/network"

  cluster = "testpad8"
  region  = "us-central1"
  domain  = "scratchpad.objectrocket.cloud"

  providers = {
    aws.env = "aws.env"
    google  = "google"
    aws     = "aws"
  }
}
```

The network module is the first part we're porting and testing with TF12. The locals/inputs are in different files in the module.
```hcl 
# DNS Setup

# Parent Zone in Route53 to create subdomains in
data "aws_route53_zone" "main" {
  provider = "aws.env"
  name     = "${var.domain}"
}

# DNS Zone in GCP for the cluster
resource "google_dns_managed_zone" "cluster" {
  name        = "${local.cluster_domain}"
  dns_name    = "${local.cluster_domain}"
  description = "Domain for CLUSTER: ${var.cluster}"
  visibility  = "public"

  labels = "${merge(var.extra_labels,
    map("Name", "${local.cluster_domain}"),
  map("launchpad_cluster", "${var.cluster}"))}"
}

# DNS delegation records in the main environment domain
resource "aws_route53_record" "environment-ns" {
  provider = "aws.env"
  zone_id  = "${data.aws_route53_zone.main.zone_id}"
  name     = "${local.cluster_domain}"
  type     = "NS"
  ttl      = "30"

  records = [
    "${google_dns_managed_zone.cluster.name_servers.*}",
  ]
}

# Create a zone for mongo product to publish records to
resource "google_dns_managed_zone" "mongo" {
  name        = "m.${local.cluster_domain}"
  dns_name    = "m.${local.cluster_domain}"
  description = "Domain for mongo records in CLUSTER: ${var.cluster}"
  visibility  = "public"

  labels = "${merge(var.extra_labels,
    map("Name", "${local.cluster_domain}"),
  map("launchpad_cluster", "${var.cluster}"))}"
}

# Create a delegation for the m.$var.cluster.$environment domain
resource "google_dns_record_set" "environment-mongo-ns" {
  managed_zone = "${google_dns_managed_zone.cluster.name}"
  name         = "m.${google_dns_managed_zone.cluster.dns_name}"
  type         = "NS"
  ttl          = "30"

  rrdatas = [
    "${google_dns_managed_zone.mongo.name_servers.*}",
  ]
}

# Create the wildcard in the mongo domain
resource "google_dns_record_set" "mongo-wildcard" {
  managed_zone = "${google_dns_managed_zone.mongo.name}"
  name         = "*"
  type         = "CNAME"
  ttl          = "30"

  rrdatas = ["${format("ingress.%s", local.cluster_domain)}"]
}

```

### Debug Output
https://gist.github.com/ephur/e8ce912655adcb1909c9b565efe2b84a

### Crash Output
N/A error message is:
```
Error: Provider configuration not present

To work with module.network.aws_route53_record.environment-ns its original
provider configuration at module.network.provider.aws.env is required, but it
has been removed. This occurs when a provider configuration is removed while
objects created by that provider still exist in the state. Re-add the provider
configuration to destroy module.network.aws_route53_record.environment-ns,
after which you can remove the provider configuration again.
```

### Expected Behavior
Plan should have executed, adding a zone in GCP, and NS records in AWS with delegations to the subdomain created in GCP. 

### Actual Behavior
Error message indicates a state that does not exist, no prior state existed. 

### Steps to Reproduce
This happens when running
```
terraform init 
terraform plan
``` 

### Additional Context
We do run terraform via a wrapper, however in this case the wrapper is not used, and it's just a test to call the module to ensure the module works as expected. The test is run manually. 

### References
I found similar issues but it looked like in each of those cases the provider configuration was being done inside of the module. In our case the provider configuration is done in the main terraform and passed into the module.

**Comment by cybojenix** [comment]
From the [docs](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly), it mentions that to have explicit providers, the module should explicitly declare it requires providers.

>In the providers map, the keys are provider names as expected by the child module, while the values are the names of corresponding configurations in the current module. The subdirectory ./tunnel must then contain proxy configuration blocks like the following, to declare that it requires configurations to be passed with these from the providers block in the parent's module block


Basically, declare a bare provider in your module, and you should be fine. This fixes the issue for us.

It would be good if this is mentioned in the upgrade guide that module providers are now explicitly required, and that this is added to the checklist, as the above paragraph is fairly easy to miss.

**Comment by Jakexx360** [comment]
> Basically, declare a bare provider in your module, and you should be fine.

How do you mean?

**Comment by cybojenix** [comment]
There are further explanations in this Issue, however this comment in particular will be useful for you @Jakexx360 
https://github.com/hashicorp/terraform/issues/21472#issuecomment-497508239

**Comment by dimisjim** [comment]
>Basically, declare a bare provider in your module, and you should be fine. This fixes the issue for us.

@ScriptMyJob For us, cutting the extra aliased provider block and pasting it inside the module that uses it, solved the problem.

**Comment by ScriptMyJob** [comment]
@cybojenix

**Comment by scalp42** [comment]
@dimisjim can you share an example?

We're passing the provider down the module already:

```hcl
# main.tf
provider "aws" {
  alias  = "dev-us-west-2"
  region = "us-west-2"

  version             = "~> 2.26"
  profile             = "dev"
  allowed_account_ids = ["xxxxx"]
}

module "iam" {
  source = "./iam"

  providers = {
    aws = aws.dev-us-west-2
  }
}
```

**Comment by dimisjim** [comment]
@scalp42 

main.tf
```
variable "region" {
  default = "eu-west-1"
}

provider "aws" {
  region  = var.region
  version = "~> 2.19.0"
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}
```

inside a module that needs to use a provider in a different region:
```
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}
```

**Comment by suksay** [comment]
I've the same issue when I use vSphere Provider

**Comment by bharathnoddy** [comment]
came across similar issue and adding a proxy provider block in my module solved it for me

Parent module config:

provider "aws" {
  alias = "test"
}

resource ... ... {
.....
....
provider = aws.test
}


code calling the parent module :
provider "aws" {
  alias = "test"
  region  = var.region

 ......  
.....
}

module ....... {
source = <reference the above module>
providers = {
awx.test = aws.test
}

**Comment by fairhaven** [comment]
@dimisjim , I used this same example, but the default provider is overriding the provider declared in the module.  Can you please be of help in any way? Thank you in advance

@scalp42 , Have you gotten this working?

**Comment by scalp42** [comment]
@fairhaven Yes, it works when respecifying the provider downstream.

**Comment by dimisjim** [comment]
@fairhaven It will override it by default. You have to explicitly specify the aliased provider in your resource block* and/or use the `--provider` flag when you import a resource into that module.

* You should have an argument like this in the resource:
```
provider = aws.us-east-1
```

**Comment by fairhaven** [comment]
provider.tf

``` provider "github" {
  organization  = xyz
  }```
```
provider "github" {
  alias  = "test"
 organization = "abc"
}
```
```
module "my_name"{
source = ./test
provider = {
github = github.test
}
```

**Comment by fairhaven** [comment]
> provider.tf
> 
> ```
>   provider "github" {
>   organization  = xyz
>   }
> 
> provider "github" {
>   alias  = "test"
>  organization = "abc"
> }
> 
> module "my_name"{
> source = ./test
> provider = {
> github = github.test
> }
> ```
> 
> So I want the module to use the second provider with alias and not the first one which served as the default provider but the default provide always override the provider with alias.

@dimisjim

**Comment by fairhaven** [comment]
> @fairhaven Yes, it works when redeclaring the provider downstream.

can this be re-worked with github provider?. Thank you for your response

**Comment by dimisjim** [comment]
@fairhaven 

The provider block should be outside of the module definition, but inside the module source itself.

PS: Try to reduce the amount of comments you post in issues. It can be annoying as people receive emails all the time.

**Comment by Ingwersaft** [comment]
I fixed it like this:

main.tf
```
provider "aws" {
  region = "eu-central-1"
}
provider "aws" {
  alias = "useast"
  region = "us-east-1"
}
module "submodule" {
  source = "./submodule"
  providers = {
    aws = aws
    aws.useast = aws.useast
  }
}
```
and in the module main.tf
```
provider "aws" {}
provider "aws" {
  alias = "useast"
}
```
After that I could use a different provider in my aws resources like outside the module.

**Comment by oraclespainpresales** [comment]
Same issue here with terraform 0.12.24. I have a main.ft with a provider and the same provider with alias.
```terraform
provider "oci" {
  version          = ">= 3.27.0"
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
}

provider "oci" {
  alias            = "home-region"
  version          = ">= 3.27.0"
  tenancy_ocid     = var.tenancy_ocid
  region           = var.region
}
```
 I've using modules to split the terraform script and I've passing providers element in the module definition.
```terraform
module "CreateCompartment" {
  source                  = "./module-compartment"
  providers               = {
    oci = oci.home-region
  }
  tenancy_ocid            = var.tenancy_ocid
  compartment_name        = var.compartment_name
  compartment_description = var.compartment_description
}
```
I've tested creating a provider in the source of the module, 
```terraform
variable "tenancy_ocid" {}
variable "compartment_description" {}
variable "compartment_name" {}

provider oci {
     alias = oci.home-region
}

//Create a new compartment and not destroy as default with
//enable_delete = false
resource "oci_identity_compartment" "CreateCompartment" {
  compartment_id = var.tenancy_ocid
  description    = var.compartment_description
  name           = var.compartment_name
  enable_delete  = false
}
```
I've tested without a provider and the result is the same 

```terraform
variable "tenancy_ocid" {}
variable "compartment_description" {}
variable "compartment_name" {}

//Create a new compartment and not destroy as default with
//enable_delete = false
resource "oci_identity_compartment" "CreateCompartment" {
  compartment_id = var.tenancy_ocid
  description    = var.compartment_description
  name           = var.compartment_name
  enable_delete  = false
}
```

<pre>
Error: Provider configuration not present

To work with
module.CreateCompartment.oci_identity_compartment.CreateCompartment its
original provider configuration at provider.oci.home-region is required, but
it has been removed. This occurs when a provider configuration is removed
while objects created by that provider still exist in the state. Re-add the
provider configuration to destroy
module.CreateCompartment.oci_identity_compartment.CreateCompartment, after
which you can remove the provider configuration again.
</pre>

**Comment by thestevenbell** [comment]
@oraclespainpresales Try this
`variable "tenancy_ocid" {}
variable "compartment_description" {}
variable "compartment_name" {}

//Create a new compartment and not destroy as default with
//enable_delete = false
resource "oci_identity_compartment" "CreateCompartment" {
  provider = oci. # <------------- ADD PROVIDER REFERENCE HERE. !!!!!!!
  compartment_id = var.tenancy_ocid
  description    = var.compartment_description
  name           = var.compartment_name
  enable_delete  = false
}`

I have not trested this method with the oci provider or this resource type, but this pattern works for Google provider resources.

**Comment by danieldreier** [comment]
I reproduced this on 0.13.0 beta 1 using the reproduction case scripted at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/21416

**Comment by zuberu23** [comment]
Hi,
I am having similar issue with terraform 0.12.26. I have tried all the solutions I can find but still it does not solve it. What is the status of it?

**Comment by jurgenweber** [comment]
@danieldreier yes, I don't seem to be able to use an explicit provider on a module in 0.13 beta 2 either. Any news here? I have all the proxy config as outlined for 0.12.

**Comment by apparentlymart** [comment]
Indeed, it does seem like @danieldreier's reproduction is missing a proxy configuration block as documented in [Passing Providers Explicitly](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly).

While improving the configuration language's modelling of required non-default provider configurations in child modules is something we'd like to do eventually, with Terraform's current design that is _supposed_ to fail, though the specific error message it returns leaves a lot to be desired because Terraform seems to be confusing it with the case where a provider configuration was _formerly_ present and has now been removed.

I'd be curious to see if there's a reproduction of this problem in situations where the proxy configuration block _is_ present. If not, perhaps we can resolve this bug for now by improving that error message to talk specifically about proxy configuration blocks, with the larger change to rework how the configuration language represents that situation left for a separate enhancement issue.

**Comment by sunnynehar56** [comment]
upgrade from 0.11.3 to 0.11.14 went fine not received any errors.
upgrading from version: 0.11.14 to 0.12.21
awsproviderversion=2.50.0

resource "aws_route53_record" "services" {
  provider = "aws.somehostedzone"                                     # resource is using provider somehostedzone
  zone_id = "${var.dns_route53_hosted_zone_id}"
  name = "${lower(var.client_id)}-services.${lower(var.dns_domain)}"
  type = "A"
  ttl = "300"
  records = ["${aws_xxxxxxxxxx_ip}"]
}
provider "aws" {
  allowed_account_ids = ["${var.TEMPLATE_AWS_ACCOUNT_ID}"]
  assume_role {
    external_id = "${var.deployment_role_external_id}"
    role_arn     = "${var.deployment_role_arn}"
    session_name = "Terraform_Deployment"
  }
  region      = "TERRAFORM_REGION"
  version = "AWS_PROVIDER_VERSION"
}

provider "aws" {
  alias = "somehostedzone"                                 # this is called in module
  region      = "TERRAFORM_REGION"
  version = "AWS_PROVIDER_VERSION"
  assume_role {
    external_id = "${var.deployment_role_external_id}"
    role_arn = "${var.aws_assume_remotehostedzone_role_arn}"
    session_name = "TerraformAccessToRemoteHostedZone"
  }
}

provider "aws" {
  alias = "deployment_account"                           # this is called in module
  region      = "TERRAFORM_REGION"
  version = "AWS_PROVIDER_VERSION"
}

module "vpc" {
  source = "git::ssh://git@..............."
  
  providers = {
    aws = aws
    aws.somehostedzone= aws.somehostedzone
    aws.deployment_account = aws.deployment_account
  }
  az_1 = "${module.environment.az_1["${lower(module.region.region)}"]}"
  ...............
  ...............
}
even after mentioning the providers under the module, still, the error persists a lot.
tfplan output

Error: Provider configuration not present

To work with module.vpc-template.aws_route53_record.example-services
its original provider configuration at
module.vpc-template.provider.aws.alfahostedzone is required, but it
has been removed. This occurs when a provider configuration is removed while
objects created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.vpc-template.aws_route53_record.example-services, after which
you can remove the provider configuration again.

Error: Provider configuration not present

To work with module.vpc-template.aws_route53_record.example-db-services
its original provider configuration at
module.vpc-template.provider.aws.alfahostedzone is required, but it
has been removed. This occurs when a provider configuration is removed while
objects created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.vpc-template.aws_route53_record.example-db-services, after which
you can remove the provider configuration again.

  ...............
  ...............

**Comment by manoadamro** [comment]
I have this error too, but only when run on CICD, running locally works just fine.

**Comment by danieldreier** [comment]
I've removed the "confirmed" label on here because as folks pointed out, my reproduction case was incorrect. In order to move forward on this, we need a reproduction of this problem in situations where the proxy configuration block is present, like Martin described, on 0.13.x or the 0.14 alpha. If someone can make a PR to update the example I'd tried to make (https://github.com/danieldreier/terraform-issue-reproductions/tree/master/21416) that would be a great place to put it.

**Comment by shrinathaithal** [comment]
I've had a odd encounter with this error in a weird scenario -   

- I use 0.11.xx terraform
- I use AWS provider. 
- ansible.tf has this - 
```
resource "aws_security_group" "ssh" {
... some good security group here without a word about provider
... it knows default provider
}
```
- I upgrade to 0.13.xx terraform
- someone deletes/moves ansible.tf to ansible.tfback, but the security group still exists in the tfstate file. 
Now it keeps throwing up the error paragraph about provider configuration missing.   
 
I add the security group config to one of the tf files in that directory, it's fine without even adding a provider block. It uses default provider block! Is it supposed to understand that this scenario has nothing to do with provider, but entire config mismatch between state and tf files?

**Comment by willthames** [comment]
@danieldreier I just ran your issue reproducer fresh from cloning it:

```
./run.sh 
+ terraform init
Initializing modules...
- example in modules/example

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v3.22.0...
- Installed hashicorp/aws v3.22.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
+ terraform validate

Error: Provider configuration not present

To work with module.example.aws_vpc.tf-21416-us-west-2 its original provider
configuration at
module.example.provider["registry.terraform.io/hashicorp/aws"].us-west-2 is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.example.aws_vpc.tf-21416-us-west-2, after which you can remove the
provider configuration again.
```

**Comment by roemmai** [comment]
> @danieldreier I just ran your issue reproducer fresh from cloning it:
> 
> ```
> ./run.sh 
> + terraform init
> Initializing modules...
> - example in modules/example
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Finding latest version of hashicorp/aws...
> - Installing hashicorp/aws v3.22.0...
> - Installed hashicorp/aws v3.22.0 (signed by HashiCorp)
> 
> Terraform has created a lock file .terraform.lock.hcl to record the provider
> selections it made above. Include this file in your version control repository
> so that Terraform can guarantee to make the same selections by default when
> you run "terraform init" in the future.
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> + terraform validate
> 
> Error: Provider configuration not present
> 
> To work with module.example.aws_vpc.tf-21416-us-west-2 its original provider
> configuration at
> module.example.provider["registry.terraform.io/hashicorp/aws"].us-west-2 is
> required, but it has been removed. This occurs when a provider configuration
> is removed while objects created by that provider still exist in the state.
> Re-add the provider configuration to destroy
> module.example.aws_vpc.tf-21416-us-west-2, after which you can remove the
> provider configuration again.
> ```
> 
> EDIT: the above was with 0.14.2, I also retried after upgrading to 0.14.3
> EDIT 2: I retried with 0.13.5 and it works _if you add a provider into the module_ (that doesn't work with 0.14.x)
> EDIT 3: Neither 0.13 nor 0.14 works with module for_each: [danieldreier/terraform-issue-reproductions#9](https://github.com/danieldreier/terraform-issue-reproductions/pull/9)

We see the same behavior with version `0.14.7` for `terraform plan + destroy` of resources that were removed from code. In previous versions code removal did not cause any issues. The plan reported that the resources would be destroyed.
Now I had to manually run `terraform destroy` on the code prior tot he removal and then remove the corresponding code afterwards.
Our scenario is as follows: Developers do not own the infrastructure but can create a pull request with the code removed. We then run a `terraform plan` as part of a validation pipeline to be able to verify what the effect of the code merge would be. This does not work anymore.

**Comment by jbardin** [comment]
Hello,

The validation of provider configurations in v0.15 will be much more strict than in previous versions, and should prevent most of the type of errors presented here. Since we're no longer actively developing v0.12, any new problems should be verified against 0.15 or later and submitted as new issues.

Thanks!
