### ISSUE TITLE
Terraform crashes with map(object(key = map(map))) variable type

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#25291]
### Terraform Version
```
Terraform v0.12.26
```

### Terraform Configuration Files
variable declaration:

```terraform
variable "iam_roles" {
  type = map(object({
    effect = string
    principal = map(any)
    condition = map(any)
  }))
  default     = {}
  description = "The IAM roles and their attributes for the account."
}
```

variable assignment:

```terraform
iam_roles = {
...
  "aws-vmimport" = {
    effect = "Allow",
    principal = { "Service" = "vmie.amazonaws.com" },
    condition = { "StringEquals" = {
      "sts:ExternalId" = "vmimport"
    }}
  },
...
}
```

### Debug Output
n/a

### Crash Output
> panic: inconsistent map element types (cty.Object(map[string]cty.Type{"condition":cty.Map(cty.DynamicPseudoType), "effect":cty.String, "principal":cty.Map(cty.String)}) then cty.Object(map[string]cty.Type{"condition":cty.Map(cty.String), "effect":cty.String, "principal":cty.Map(cty.String)}))
goroutine 211 [running]:
github.com/zclconf/go-cty/cty.MapVal(0xc0008bd458, 0xc0008bd400, 0xc000831360, 0xc, 0xc0008bd570)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/value_init.go:207 +0x538
github.com/zclconf/go-cty/cty/convert.conversionObjectToMap.func2(0x246a000, 0xc0004921e8, 0x1bd0d80, 0xc0007a11d0, 0xc000db0ee0, 0x1, 0x1, 0xc000506700, 0x10, 0x10, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion_collection.go:338 +0x555
github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x246a000, 0xc0004921e8, 0x1bd0d80, 0xc0007a11d0, 0x0, 0x0, 0x0, 0xc0006baed0, 0xc000db0ed0, 0x2469fc0, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:46 +0x1ad
github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x246a000, 0xc0004921e8, 0x1bd0d80, 0xc0007a11d0, 0xc000db0ed0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:179 +0x6b
github.com/zclconf/go-cty/cty/convert.Convert(0x246a000, 0xc0004921e8, 0x1bd0d80, 0xc0007a11d0, 0x2469fc0, 0xc00014d3d0, 0x0, 0x246a000, 0xc0004921e8, 0x1bd0d80, ...)
	/opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/public.go:51 +0x1af
github.com/hashicorp/terraform/terraform.(*EvalModuleCallArgument).Eval(0xc00095f500, 0x249fe60, 0xc0007a40d0, 0x2, 0x2, 0xc000226000, 0x42)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_variable.go:77 +0x160
github.com/hashicorp/terraform/terraform.EvalRaw(0x2424a20, 0xc00095f500, 0x249fe60, 0xc0007a40d0, 0x2d, 0x0, 0x0, 0x2d)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc0004b2b70, 0x249fe60, 0xc0007a40d0, 0x2, 0x2, 0xc000bd4b38, 0x42b8a1)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x2424a60, 0xc0004b2b70, 0x249fe60, 0xc0007a40d0, 0x14, 0xbfb3022e070510f8, 0x2c0ca496, 0x2d)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0005a8c20, 0x249fe60, 0xc0007a40d0, 0x2, 0x2, 0xf3e5f5, 0x2425100)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2424bc0, 0xc0005a8c20, 0x249fe60, 0xc0007a40d0, 0x1bc1420, 0x3547785, 0x1b24b60, 0xc000db0a80)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2424bc0, 0xc0005a8c20, 0x249fe60, 0xc0007a40d0, 0xc0005a8c20, 0x2424bc0, 0xc0005a8c20, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1d8e520, 0xc0004b4b40, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0007a6000, 0x1d8e520, 0xc0004b4b40, 0xc00095e380)
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

### Expected Behavior
Terraform does not crash.

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
`terraform validate`

### Additional Context
I really cannot figure out how to provide additional information for this since I am not sure why it crashed or what the stack trace indicates. I am only filing this issue since the crash output suggested it. This could all be due to an error on my part, but I have no idea how to determine that since it crashed.

This is also eventually passed into a `assume_role_policy = templatefile("${path.root}/policies/assume_role.tmpl", { effect = each.value.effect, principal = each.value.principal, condition = each.value.condition })` where the relevant template content is:

```
%{ if condition != null }
"Condition": ${jsonencode(condition)},
%{ endif }
```

### References
n/a

**Comment by jbardin** [comment]
Hi @mschuchard,

Yes, the output here is not the best feedback for the issue at hand. 

What I suspect is going on, is that all types in a map must be identical. Defining the element object attributes like `condition = map(any)` doesn't mean that each map element can have a different type, just that they could have any type as long as all elements have the same structure. 

I suspect that if you try this with the 0.13 beta, you'll get a slightly better error about `collection elements cannot be unified.`, rather than a panic.

Since maps must contain identical element types, the only way to have this sort of dynamic structure at the moment is to have it infer the correct type at runtime, which means you have to resort to `type = any`. It may be better to define a structure using a superset of the possible field types, or break up the parameters into separate structures.

**Comment by jbardin** [comment]
Truthfully, I'm not sure what is required there or if it's possible, since it depends on what you're doing with the data, or what the resource expects. Flattening things into `map(string)`, or adding different fields for the different possible structures may work.

If the crash if fixed in 0.13, we can probably close this particular issue out. As for structuring the data, [the community forum](https://discuss.hashicorp.com/c/terraform-core) may have more users familiar with the particulars of the aws resources and experience building modules with them.

**Comment by mschuchard** [comment]
Just a quick note changing the type to `map(any)` throws:
> all map elements must have the same type
so does appear to be root cause.

and terraform 0.13-beta2 throws:
> The given value is not suitable for child module variable "iam_roles" defined
at ../h3-terraform-aws-iam/variables.tf:46,1-21: collection elements cannot be
unified.

so the crash is fixed; closing.

I will just try to code a workaround for this in the interim. Thanks!

**Comment by mschuchard** [comment]
Ok so I should mention that I changed the values to all be `map(string)` type so they are all the same, and it still crashes on Terraform 0.12, but the 0.13-beta2 validates successfully.

Is there a chance the fix can be backported to 0.12? It seems like this has produced a bug that the following crashes 0.12:

```terraform
type = map(object({
    effect = string
    principal = map(string)
    condition = map(string)
  }))
```

but is valid in 0.13, and it really should be valid for 0.12 as well I would think.

**Comment by jbardin** [comment]
A fields of `condition = map(any)` within a map is valid as long as all the values being inserted have the same type, but there are some codepaths that don't handle the unification properly. The bug fix essentially is that there is better validation that no longer reaches the point of panicking.

If there are any further 0.12 releases, they would only be for extremely urgent issues, and would not include major backports.

**Comment by jbardin** [comment]
As for `null`, it can be assigned to any type in HCL. What I suspect you're getting at hat there is a problem using null with nested type `any`?

Since this didn't work at all on 0.12, I would suggest seeing if you can create a reproduction of the problem with the 0.13 beta.

**Comment by mschuchard** [comment]
Ok, then I will be sure to never use `map(any)` for the time being in 0.12. Thanks!
