### ISSUE TITLE
Terraform crash with 0.14.5 and sensitive variable - panic: value is marked, so must be unmarked first

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform#27596]
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/iwarapter/pingfederate v0.0.8
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    pingfederate = {
      source  = "iwarapter/pingfederate"
      version = "0.0.8"
    }
  }
}

provider "pingfederate" {
  password = "2FederateM0re"
}

resource "pingfederate_notification_publisher" "mailserver" {
  name         = "demo"
  publisher_id = "demo"
  plugin_descriptor_ref {
    id = "com.pingidentity.email.SmtpNotificationPlugin"
  }

  configuration {
    fields {
      name  = "From Address"
      value = "someone@test.com"
    }
    fields {
      name  = "Email Server"
      value = "email-smtp.eu-west-1.amazonaws.com"
    }
    fields {
      name  = "SMTP Port"
      value = "25"
    }
    fields {
      name  = "Encryption Method"
      value = "SSL"
    }
    fields {
      name  = "SMTPS Port"
      value = "465"
    }
    fields {
      name  = "Verify Hostname"
      value = "false"
    }
    fields {
      name  = "Username"
      value = "someone"
    }
    sensitive_fields {
      name  = "Password"
      value = var.mail_server_password
    }
    fields {
      name  = "Test Address"
      value = "example@test.com"
    }
    fields {
      name  = "Connection Timeout"
      value = "30"
    }
    fields {
      name  = "Retry Attempt"
      value = "2"
    }
    fields {
      name  = "Retry Delay"
      value = "2"
    }
    fields {
      name  = "Enable SMTP Debugging Messages"
      value = "false"
    }
  }
}

variable "mail_server_password" {
  type      = string
  sensitive = true
}
```

### Crash Output

https://gist.github.com/iwarapter/3d151bcd232512e493c3d1851058bb60

### Expected Behavior

Apply succeeds as with tf-0.13.x

### Actual Behavior

 Panic Crash

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

There have been a few other issues where this has presented - https://github.com/hashicorp/terraform/search?q=panic%3A+value+is+marked%2C+so+must+be+unmarked+first&type=issues however most say to upgrade to 0.14.(4/5)

**Comment by pselle** [comment]
@iwarapter Thanks for reporting this! That error is a sign of a bug, but can happen in many cases. Reading your scenario here, do you have the experimental `provider_sensitive_attrs` experiment enabled?

I ask this because the provider defines the field you're passing the sensitive variable to as sensitive:
https://github.com/iwarapter/terraform-provider-pingfederate/blob/2701b6cb5ae50c6a5b73e30d482b10dad7cbc37b/pingfederate/structures.go#L640, but I don't see that experiment in the config you have. 

You shouldn't run into this error, but if you _do_ have the experiment enabled, one way to work around (and still get the redaction you're expecting) is to remove the `sensitive=true` on that variable, because it's redundant.

**Comment by iwarapter** [comment]
Hi @pselle Thanks for looking at this, no I don't have that experiment enabled. Whilst I can remove the flag from the variable i actually found this on a bigger project where the value gets used on this sensitive and on another non sensitive field somewhere (but this was the smallest reproducer).

I have pushed the reproducer https://github.com/iwarapter/tf-0.14-panic-marked-unmarked/blob/main/main.tf - i'll add a quick readme on setting up a quick local env if you want to try it.

**Comment by pselle** [comment]
@iwarapter That's be appreciated! I'm guessing at the provider's structure (as gets translated through the SDK into Core concepts) and it would be good to validate that what I _think_ will fix it will _actually_ fix your issue.

**Comment by iwarapter** [comment]
I have pushed the readme and docker-compose.

**Comment by pselle** [comment]
@iwarapter I really really appreciate you sharing the reproduction repo, and I have spent a few hours trying to interact with this image, but am failing, after trying different settings in the `docker-compose`, changing settings in the `provider` block ... I suspect I haven't succeeded in getting a working image going, so may I ask you to take another look at your reproduction and confirm that it works for you (I did add credentials)?

**Comment by iwarapter** [comment]
hi @pselle as long as you have set both the environment variables credentials (you need to register https://devops.pingidentity.com/get-started/devopsRegistration/) to get them.
```
➜  tf-0.14-panic-marked-unmarked git:(main) ✗ env | grep PING_IDENTITY
PING_IDENTITY_DEVOPS_USER=*****
PING_IDENTITY_DEVOPS_KEY=*****
➜  tf-0.14-panic-marked-unmarked git:(main) ✗ docker-compose up -d
Creating network "tf-014-panic-marked-unmarked_pingnet" with the default driver
Creating tf-014-panic-marked-unmarked_pingfederate_1 ... done
➜  tf-0.14-panic-marked-unmarked git:(main) ✗ docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS                        PORTS                                            NAMES
297f05738753        pingidentity/pingfederate:10.0.6-edge   "./bootstrap.sh star…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:9031->9031/tcp, 0.0.0.0:9999->9999/tcp   tf-014-panic-marked-unmarked_pingfederate_1
➜  tf-0.14-panic-marked-unmarked git:(main) ✗ terraform init
etc etc
```
If you still getting issues paste me the container logs :)

**Comment by pselle** [comment]
Well, the trick of "ask, and then it will work" worked, I think there might've been a delay in getting a license.

I've replicated your issue and wrote a fix (fwiw, that config still doesn't apply will provide error below, but maybe that's expected since this is for reproducing the panic) but at least you avoid the panic! Now the tricky bit of writing a test to replicate this codepath.

```

pingfederate_notification_publisher.mailserver: Creating...
╷
│ Error: unable to create NotificationPublishers: Validation error(s) occurred. Please review the error(s) and address accordingly.
│ The plugin ID is already defined, specify a unique ID.
│ 
│ 
╵
```

**Comment by iwarapter** [comment]
Hehe yeah it takes a minute or two to get started. I just ran the apply with debug logging fully and I can see it does indeed create the resource and panic and die with nothing in the statefile
```
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 2021/01/29 19:49:41 DEBUG: Request NotificationPublishers/CreateNotificationPublisher: 01e464be-176d-4756-8a44-b5ab7c88391c
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: ---[ REQUEST ]--------------------------------------
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: POST /pf-admin-api/v1/notificationPublishers HTTP/1.1
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Host: localhost:9999
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Authorization: ********
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Content-Type: application/json
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: User-Agent: pingfederate-sdk-go/10.0.2.2 (go1.13.15; darwin; amd64)
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: X-Xsrf-Header: pingfederate
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: {"configuration":{"fields":[{"inherited":false,"name":"SMTP Port","value":"25"},{"inherited":false,"name":"Verify Hostname","value":"false"},{"inherited":false,"name":"Encryption Method","value":"SSL"},{"inherited":false,"name":"SMTPS Port","value":"465"},{"inherited":false,"name":"Retry Delay","value":"2"},{"inherited":false,"name":"Connection Timeout","value":"30"},{"inherited":false,"name":"From Address","value":"someone@test.com"},{"inherited":false,"name":"Retry Attempt","value":"2"},{"inherited":false,"name":"Test Address","value":"example@test.com"},{"inherited":false,"name":"Enable SMTP Debugging Messages","value":"false"},{"inherited":false,"name":"Email Server","value":"email-smtp.eu-west-1.amazonaws.com"},{"inherited":false,"name":"Username","value":"someone"},{"inherited":false,"name":"Password","value":"secret"}]},"id":"demo","name":"demo","pluginDescriptorRef":{"id":"com.pingidentity.email.SmtpNotificationPlugin"}}
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 
2021-01-29T19:49:41.621Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: -----------------------------------------------------
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 2021/01/29 19:49:41 DEBUG: Response NotificationPublishers/CreateNotificationPublisher: 01e464be-176d-4756-8a44-b5ab7c88391c
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: ---[ RESPONSE ]--------------------------------------
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: HTTP/1.1 201 Created
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Transfer-Encoding: chunked
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Cache-Control: no-cache, no-store
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Content-Type: application/json
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Date: Fri, 29 Jan 2021 19:49:41 GMT
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Expires: 0
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Location: https://localhost:9999/pf-admin-api/v1/notificationPublishers/demo
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: Pragma: no-cache
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 40a
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: {"id":"demo","name":"demo","pluginDescriptorRef":{"id":"com.pingidentity.email.SmtpNotificationPlugin","location":"https://localhost:9999/pf-admin-api/v1/notificationPublishers/descriptors/com.pingidentity.email.SmtpNotificationPlugin"},"configuration":{"tables":[],"fields":[{"name":"SMTP Port","value":"25"},{"name":"Verify Hostname","value":"false"},{"name":"Encryption Method","value":"SSL"},{"name":"SMTPS Port","value":"465"},{"name":"From Address","value":"someone@test.com"},{"name":"Test Address","value":"example@test.com"},{"name":"Email Server","value":"email-smtp.eu-west-1.amazonaws.com"},{"name":"Username","value":"someone"},{"name":"Password","encryptedValue":"OBF:JWE:eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiUWVzOVR5eTV5WiIsInZlcnNpb24iOiIxMC4wLjYuMSJ9..43_FNi2WDNUhjZnzXrINGQ.5LuBlU38z1yaiZ0M6knGBg.HoIWujQMk7YvS43mQbnbFA"},{"name":"Retry Delay","value":"2"},{"name":"Connection Timeout","value":"30"},{"name":"Retry Attempt","value":"2"},{"name":"Enable SMTP Debugging Messages","value":"false"}]}}
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 0
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: 
2021-01-29T19:49:41.988Z [DEBUG] plugin.terraform-provider-pingfederate_v0.0.8: -----------------------------------------------------
```

You'd need to clear the resource out manually:
```
curl -k -X DELETE -H "X-Xsrf-Header: pingfederate" --user Administrator:2FederateM0re   https://localhost:9999/pf-admin-api/v1/notificationPublishers/demo -i
HTTP/1.1 204 No Content
Date: Fri, 29 Jan 2021 19:54:29 GMT
Content-Type: application/json
Expires: 0
Pragma: no-cache
Cache-Control: no-cache, no-store
```
