### ISSUE TITLE
Provider produced inconsistent final plan while using for loop for creating variables

### ISSUE THREAD

**Issue by rajivreddy** [hashicorp/terraform#28051]
### Terraform Version

```
terraform version 
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.31.0

Your version of Terraform is out of date! The latest version
is 0.14.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
# Reserve Elastic IP for NLB

resource "aws_eip" "this" {
  count = var.number_of_eips
  vpc               = var.vpc
  tags = var.tags
}


module "nlb" {
  source             = "../lb-module"
  enable             = true
  name               = var.loadbalancer_name
  load_balancer_type = "network"
  internal           = false
  subnets = var.number_of_eips == 0 ? var.subnet_ids : null
  vpc_id             = var.vpc_id
  tags                 = var.tags

  subnet_mapping = var.number_of_eips > 0 ? flatten([
      for k,v in zipmap(aws_eip.this.*.id,var.subnet_ids): {
          subnet_id = v
          allocation_id = k
      }
  ]) : []

  ### For Target Groups
  target_groups = var.target_groups
  http_tcp_listeners = var.http_tcp_listeners
  depends_on = [
    aws_eip.this
  ]


  
}

### Needs review
resource "aws_lb_target_group_attachment" "b2b_nlb_prove_lower_tga" {
    count = length(var.target_ips)
    target_group_arn = join("", module.nlb.target_group_arns)
    target_id = var.target_ips[count.index]
    availability_zone = "all"
    port             = 443
}

```

### Crash Output

```
2021/03/11 18:25:13 [WARN] Provider "registry.terraform.io/hashicorp/aws" produced an unexpected new value for module.example_ingress_nlb_module.aws_eip.this[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .customer_owned_ipv4_pool: was null, but now cty.StringVal("")
2021-03-11T18:25:13.614+0530 [INFO]  plugin.terraform-provider-aws_v3.31.0_x5: 2021/03/11 18:25:13 [WARN] Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-03-11T18:25:13.614+0530
2021-03-11T18:25:13.614+0530 [INFO]  plugin.terraform-provider-aws_v3.31.0_x5: 2021/03/11 18:25:13 [WARN] Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-03-11T18:25:13.614+0530
2021/03/11 18:25:13 [WARN] Provider "registry.terraform.io/hashicorp/aws" produced an invalid plan for module.example_ingress_nlb_module.module.nlb.aws_lb.this[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .idle_timeout: planned value cty.NullVal(cty.Number) does not match config value cty.NumberIntVal(60)
      - .security_groups: planned value cty.UnknownVal(cty.Set(cty.String)) does not match config value cty.SetValEmpty(cty.String)
2021/03/11 18:25:13 [ERROR] eval: *terraform.EvalCheckPlannedChange, err: Provider produced inconsistent final plan: When expanding the plan for module.example_ingress_nlb_module.module.nlb.aws_lb.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .subnet_mapping: block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021/03/11 18:25:13 [ERROR] eval: *terraform.EvalSequence, err: Provider produced inconsistent final plan: When expanding the plan for module.example_ingress_nlb_module.module.nlb.aws_lb.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .subnet_mapping: block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021-03-11T18:25:13.665+0530 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-11T18:25:13.673+0530 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/aws/3.31.0/darwin_amd64/terraform-provider-aws_v3.31.0_x5 pid=67622
2021-03-11T18:25:13.673+0530 [DEBUG] plugin: plugin exited
```

### Expected Behavior

Should be able to create a Loadbalancer with subnet mapping

### Actual Behavior

It throwing error message 
```log
hen expanding the plan for
module.example_ingress_nlb_module.module.nlb.aws_lb.this[0] to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.subnet_mapping: block set length changed from 1 to 2.
```

### Steps to Reproduce

```bash
terraform init
terraform apply
```

**Comment by jbardin** [comment]
Hi @rajivreddy 

Thanks for filing the issue. We will need more information to try and determine what the issue might be here. The error message indicates that the `module.example_ingress_nlb_module.module.nlb.aws_lb.this[0]` resource is what caused the error, but that resource is not present in the given configuration. Can you provider a more complete example which we could use to reproduce the problem? If it's possible, can you confirm that this is an issue with the current release version as well?

Thanks!

**Comment by rajivreddy** [comment]
Hi @jbardin ,
You can find the complete code here
https://github.com/foss-cafe/terraform-elb-issue

**Comment by jbardin** [comment]
Thanks @rajivreddy,

This appears to be the same case fixed by #26638. Can you verify this is still an issue in the latest release?

**Comment by rajivreddy** [comment]
We tested with Terraform `0.14.8` version, but the issue still persist.

**Comment by jbardin** [comment]
Thanks for the example @rajivreddy. I took the linked module and applied it successfully with 0.14.8 and the latest 0.15 build after adding the necessary prerequisites. 

Could you fill in the configuration with a sample of the infrastructure you used that reproduces the error?

Thanks!

**Comment by magodo** [comment]
@jbardin I can confirm that the config in #25600 still exists in terraform v0.14.8.

**Comment by jbardin** [comment]
@magodo, thanks for the info. This however is a different issue, which just happens to be caught during the same validation. Any change here needs to come from the provider, and the linked azurerm issue is what I would follow for the problem you mention in 25600.

**Comment by magodo** [comment]
Hi @jbardin, I didn't get your point. Do you mean #25600 has been resolved. Then how does the issue still exist when using v0.14.8?

**Comment by jbardin** [comment]
@magodo, The component of #25600 which was caused by terraform itself has been resolved. The remaining issue as it pertains to the example shown is caused by the data being returned to terraform from the provider, and is being tracked as an issue in the provider repository. A resolution would have to come from from a change to the provider, or possibly the provider SDK.

**Comment by magodo** [comment]
@jbardin I don't think there is anything can be done at provider level? Do you mean that updating the provider SDK to v2 might address this issue?

**Comment by jbardin** [comment]
Hi @magodo,

This issue is still waiting for confirmed reproduction, so I do not know if relates to the issue you linked. The case presented in #25600 has been resolved within terraform itself, but that does not prevent the provider from causing that error on its own. From my notes on the previous issue, the provider is unexpectedly altering the value used for the dynamic block by inserting default values where they should not be set. This is not something fixed by the SDKv2, nor do I know if it's something that the SDK can handle until a next-gen release that works entirely within the new plugin protocol. 

Let me see if I can still reproduce that from the given example, and we can continue the conversation in the open provider issue.

@rajivreddy, This issue is still waiting for a standalone reproduction in order to investigate further. It would be a great help if you could modify the example you provided so that it demonstrates the problem in isolation.

**Comment by magodo** [comment]
@jbardin Can we reopen the #25600 to track the provider related issue there? TBH, I've tried to remove the dynamic block for the `log` (only keeps `metric`) as there is no `log` returned from the data source for that resource. Whilst the error still exists:

```bash
Error: Provider produced inconsistent final plan

When expanding the plan for azurerm_monitor_diagnostic_setting.test to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.metric: block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by jbardin** [comment]
@magodo, I'm working on a plan to try and handle this for providers transparently, and will be tracking the issue in #28340.

Thanks!

**Comment by jbardin** [comment]
Since we have not heard back about the original issue in a while I'm going to close this out. If there is still a reproducible problem with the latest Terraform release, please feel free to update this issue or file a new one with all the details necessary for the reproduction.

Thanks!
