### ISSUE TITLE
"Terraform destroy" is removing dependencies from a resource which fails to delete

### ISSUE THREAD

**Issue by ujjwal-ibm** [hashicorp/terraform#28315]
### Terraform Version

Terraform v0.14.6
...
```

### Terraform Configuration Files

resource “r1” “this”{
}
resource “r2” “this”{
key = r1.this.id
}
resource “r3” “this”{
key = r2.this.id
}
resource “r4” “this”{
key = r3.this.id
}
resource “r5” “this”{
key = r4.this.id
}
resource “r6” “this”{
key = r5.this.id
}

### Debug Output
Error: Error deleting r4

### Crash Output


### Expected Behavior

1. r4 deletion should fail, works expected and the rest of the destroy should stop. This works expected.
2. No change in r4 in terraform.state file

### Actual Behavior
1. since r4 is having dependencies on r3, r2, r1. They should remain intact but this is getting removed.
2. two keys, "private" and "dependencies" are getting removed from the state file from the r4 resource.


### Steps to Reproduce
1. have a nested group of resources
2. structure a failure in deletion of a resource in middle, which is dependent on others and others are dependent on it.
3. do terraform destroy
4. ideally it should fail at r4, like in my example and once the underlying logic is resolved, destroy should destroy the other resources
5. since the dependencies are getting removed from the failed resource in state file, it is acting as an independent resource
6. so destroying it the second time is creating a situation

### Additional Context
terraform state file after apply :

 {
  "version": 4,
  "terraform_version": "0.14.6",
  "serial": 42,
  "lineage": "jdeofjo",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "r4",
      "name": "r4",
      "provider": "custom",
      "instances": [
      {
      "schema_version" : 0,
      "attributes": {}
      "sensitive_attributes": [],
      "private": "ehfihihfie",
      "dependencies": ["r3", "r2", r1"] } ]}
      
      
      terraform state file after deletion failure on r4 :

 {
  "version": 4,
  "terraform_version": "0.14.6",
  "serial": 42,
  "lineage": "jdeofjo",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "r4",
      "name": "r4",
      "provider": "custom",
      "instances": [
      {
      "schema_version" : 0,
      "attributes": {}
      "sensitive_attributes": []
       } ]}

**Comment by jbardin** [comment]
Hi @ujjwal-ibm,

Thanks for filing the issue! Do you have a working example that you can test? I suspect that this is fixed in the development releases, and it would be good to verify with 0.15.0-rc2.

**Comment by jbardin** [comment]
No need for the reproduction, I found the change (#27503) that was intended to cover this, but there is one hole still where the dependencies are not restored. If the provider is deleting a resource, and returns an error, and returns a new state for the resource, we are not restoring the old Dependencies.

**Comment by ujjwal-ibm** [comment]
Hi @jbardin ,
The provider here is not returning a new state for the resource r4 in my example. Resource r4 is still in the same state. Afaik, dependencies are inferred based on the configuration, which is still the same. Only the ones which are below r4 got destroyed, so r4's state is still the same.

**Comment by jbardin** [comment]
@ujjwal-ibm,

Thanks, the details I was referring to are only relevant in the 0.15 codebase, as the internals have changed significantly since v0.14.6.
