### ISSUE TITLE
Terraform Show fails if plan has no changes

### ISSUE THREAD

**Issue by dnascimento** [hashicorp/terraform#29042]
### Terraform Version
```
Terraform v1.0.1 (not in v1.0.0)
```

### Crash Output
```
2021-06-26T14:40:49.232+1000 [TRACE] provider.stdio: waiting for stdio data
2021-06-26T14:40:49.303+1000 [TRACE] GRPCProvider: Close
2021-06-26T14:40:49.304+1000 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-06-26T14:40:49.306+1000 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.47.0/darwin_amd64/terraform-provider-aws_v3.47.0_x5 pid=20348
2021-06-26T14:40:49.306+1000 [DEBUG] provider: plugin exited
2021-06-26T14:40:49.306+1000 [TRACE] terraform.NewContext: complete
2021-06-26T14:40:49.307+1000 [TRACE] backend/local: finished building terraform.Context

panic: value is marked, so must be unmarked first

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	github.com/zclconf/go-cty@v1.8.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x38c2e30, 0xc0005e4000, 0x3159ee0, 0xc0004587e0, 0x38c2e01)
	github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1050 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc0005e4960, 0x1, 0x1, 0x38c2e30, 0xc0005e4000, 0x3159ee0, 0xc0004587e0, 0x388c048, 0xc000458b10, 0xc0004587e0, ...)
	github.com/zclconf/go-cty@v1.8.4/cty/walk.go:144 +0x2e8
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x38c2df8, 0xc0005e4240, 0x3065f60, 0xc001a9d380, 0x388c048, 0xc000458b10, 0xc0005e48b0, ...)
	github.com/zclconf/go-cty@v1.8.4/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	github.com/zclconf/go-cty@v1.8.4/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x38c2df8, 0xc0005e4240, 0x3065f60, 0xc001a9d380, 0xc000fc4660, 0x1, 0x1, 0x38221c0, 0x1, 0xc001929640, ...)
	github.com/zclconf/go-cty@v1.8.4/cty/marks.go:236 +0xc5
github.com/hashicorp/terraform/internal/command/jsonstate.marshalResources(0xc001b0d4d0, 0x0, 0x0, 0x0, 0xc00063efd0, 0x0, 0xc00108f410, 0x13dc26c, 0xc00108f4a0, 0x34366ba)
	github.com/hashicorp/terraform/internal/command/jsonstate/state.go:333 +0xe07
github.com/hashicorp/terraform/internal/command/jsonstate.marshalRootModule(0xc000eec0a0, 0xc00063efd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform/internal/command/jsonstate/state.go:200 +0x12d
github.com/hashicorp/terraform/internal/command/jsonstate.(*state).marshalStateValues(0xc001a9c1e0, 0xc000eec0a0, 0xc00063efd0, 0x0, 0x0)
	github.com/hashicorp/terraform/internal/command/jsonstate/state.go:166 +0x14a
github.com/hashicorp/terraform/internal/command/jsonstate.Marshal(0xc001b0d3e0, 0xc00063efd0, 0x0, 0x0, 0x0, 0x0, 0x2da4e55)
	github.com/hashicorp/terraform/internal/command/jsonstate/state.go:146 +0xf8
github.com/hashicorp/terraform/internal/command/jsonplan.Marshal(0xc0005ca000, 0xc000dd3a40, 0xc001b0d3e0, 0xc00063efd0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform/internal/command/jsonplan/plan.go:152 +0x633
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0xc00048b6c0, 0xc00004e0e0, 0x1, 0x2, 0xc00058e590)
	github.com/hashicorp/terraform/internal/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc000837400, 0xc00049c060, 0x3435241, 0x4)
	github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	github.com/hashicorp/terraform/main.go:384 +0x1112
main.realMain(0x0)
	github.com/hashicorp/terraform/main.go:115 +0x554
main.main()
	github.com/hashicorp/terraform/main.go:58 +0x25
```

### Steps to Reproduce

```
terraform plan -out=plan.out
terraform show -json plan.out
```

Regression introduced by v1.0.1

**Comment by DotNetSparky** [comment]
I can confirm I get the same error even if the plan has changes (same situation: trying to generate a JSON version of a saved plan file).

I can do a non-JSON show (e.g. "terraform show plan.out") but the crash occurs when including the '-json' option.

**Comment by m-torin** [comment]
This error likes to show up with Google Cloud Run, where constant small meta tweaks by GCP means the state will have something to change every run. I'm also noticing it with GCP domain mapping and waiting for SSL certificates.

**Comment by blakemorgan** [comment]
I can confirm the same error using the AWS provider.

**Comment by davidalger** [comment]
Pretty sure this has to do with changes introduced in #28889. We updated a test branch to run Terraform (v1.0.1) plans on all of our pipelines and only a handful of our stacks crash with this new `panic: value is marked, so must be unmarked first` error but all of them with the exact same trace as the OP. Our CI plan jobs show the JSON plan to print a summarized list of changed resources, so this bug completely fails the normal CI operations on affected pipelines. In every case though, showing the plan normally, i.e. `terraform show plan.cache` works as expected but `terraform show -json plan.cache` panics.

Notably this also doesn't appear to be specific to using a cached plan. The same environments for which JSON output of a cached plan fails will also fail when running `terraform show -json` leading me to believe some edge case in the state is triggering the bug.

**Comment by mildwonkey** [comment]
Thanks for reporting this, and sorry for the bad behavior! 

It was easy enough to find where these panics occur, but I'm having trouble writing a test that can reproduce the issue. @blakemorgan or @dnascimento , can either of you share your configuration, or (better yet) provide a simplified reproduction case? It would help me to have an example I can run locally to confirm what's happening. 


---  
For a bit of an explanation: 

The panicking code is the last line, here: 
https://github.com/hashicorp/terraform/blob/main/internal/command/jsonstate/state.go#L326-L334

The call to `ResourceInstanceObjectSrc.Decode`  (at the top of the snippet above) would have already re-applied any marks, so it seems like a redundant call. However writing a test with marked attribute values isn't enough to recreate the panic; I could be miswriting the test, or the problem might require some other element to reproduce.

**Comment by mildwonkey** [comment]
I've opened a PR that removes the redundancy from the jsonstate resource marshaling - the top of the stack trace - but I wasn't actually able to coerce the panic in a test. So while removing the redundancy is a good idea regardless, I'd still like to know what actual confluence of events causes the panic so I can extend the test cases and confirm that this fixes all of the issue, and not just a symptom.

**Comment by apparentlymart** [comment]
I've not dug in deep here so I'm not sure if this is actually relevant but I see that there's a call to `cty.TransformWithTransformer` in these stack traces and wanted to note that for an unrelated reason last week I pushed [support for marks in the walk/transform functions](https://github.com/zclconf/go-cty/commit/5f5dfca48938546b1b926f46be0bd884e91aa96e) which I _think_ would make these situations not panic anymore.

I've not yet included it in a release of my `cty` library but if we can find some way to test with that `cty` commit in place and see that it helped then I'd be happy to expedite a `cty` release to help get this panic fixed.

**Comment by davidalger** [comment]
@mildwonkey I spent a little time today chasing down what I could to create a test that reproduces the issue by adding a little logging code: https://github.com/hashicorp/terraform/commit/7a9d5417d2bee93a95c6b6a02de9b4e97cc92056

Running this on one of the environments which was experiencing the panic resulted in the following:

```
$ (cd ~/work/hashicorp/terraform; go build) && ~/work/hashicorp/terraform/terraform show -json

// lots of output //

--> module.parent.module.child.kubernetes_secret.jwt_auth
(*states.ResourceInstanceObjectSrc)(0xc002700400)({
 SchemaVersion: (uint64) 0,
 AttrsJSON: ([]uint8) (len=9 cap=9) {
  00000000  52 45 41 44 41 43 54 45  44                       |READACTED|
 },
 AttrsFlat: (map[string]string) <nil>,
 AttrSensitivePaths: ([]cty.PathValueMarks) (len=1 cap=1) {
  (cty.PathValueMarks) {
   Path: (cty.Path) (len=1 cap=1) {
    (cty.GetAttrStep) {
     pathStepImpl: (cty.pathStepImpl) {
     },
     Name: (string) (len=4) "data"
    }
   },
   Marks: (cty.ValueMarks) (len=1) {
    (marks.valueMark) (len=9) "sensitive": (struct {}) {
    }
   }
  }
 },
 Private: ([]uint8) (len=4 cap=4) {
  00000000  6e 75 6c 6c                                       |null|
 },
 Status: (states.ObjectStatus) ObjectReady,
 Dependencies: ([]addrs.ConfigResource) {
 },
 CreateBeforeDestroy: (bool) false
})
{
            "binary_data": null,
            "data": {
              "client_id": "READACTED",
              "client_secret": "READACTED",
              "jwt_sign_key": "READACTED"
            },
            "id": "READACTED/jwt-auth",
            "metadata": [
              {
                "annotations": {},
                "generate_name": "",
                "generation": 0,
                "labels": {},
                "name": "jwt-auth",
                "namespace": "READACTED",
                "resource_version": "READACTED",
                "uid": "READACTED"
              }
            ],
            "type": "Opaque"
          }
panic: value is marked, so must be unmarked first

// crash backtrace redacted for brevity
```

Based on this, I threw together a test case which successfully triggers the panic: https://github.com/davidalger/terraform/commit/8a9be61f808b6504c32e30cd6c5d97cec7bc5c78

```
davidalger@silver-bullet:~/.../hashicorp/terraform (issue-29042-test-case) $ go test -run ^TestMarshalResources$ github.com/hashicorp/terraform/internal/command/jsonstate
--- FAIL: TestMarshalResources (0.00s)
    --- FAIL: TestMarshalResources/resource_with_marked_map_attr (0.00s)
panic: value is marked, so must be unmarked first [recovered]
	panic: value is marked, so must be unmarked first

goroutine 9 [running]:
testing.tRunner.func1.2(0x1a396c0, 0x1d4c470)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc00042cf00)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x1a396c0, 0x1d4c470)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/opt/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x1d71668, 0xc000473780, 0x1ac2d20, 0xc0004fe048, 0x1d71601)
	/opt/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1050 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc000473880, 0x1, 0x1, 0x1d71668, 0xc000473780, 0x1ac2d20, 0xc0004fe048, 0x1d66f90, 0xc0004fe0d8, 0xc0004fe048, ...)
	/opt/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:175 +0x8f9
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x1d716a0, 0xc000473790, 0x1a7b560, 0xc0004fa450, 0x1d66f90, 0xc0004fe0d8, 0xc000473810, ...)
	/opt/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/opt/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x1d716a0, 0xc000473790, 0x1a7b560, 0xc0004fa450, 0xc0004d4420, 0x1, 0x1, 0x1d49cb8, 0x1, 0x1b92a67, ...)
	/opt/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:236 +0xc5
github.com/hashicorp/terraform/internal/command/jsonstate.marshalResources(0xc0004e94a0, 0x0, 0x0, 0x0, 0xc000473040, 0x100000001, 0xc00006cf48, 0x107055b, 0x894940bcfbfd0, 0xc00cdfd278)
	/Users/davidalger/work/hashicorp/terraform/internal/command/jsonstate/state.go:334 +0xe07
github.com/hashicorp/terraform/internal/command/jsonstate.TestMarshalResources.func1(0xc00042cf00)
	/Users/davidalger/work/hashicorp/terraform/internal/command/jsonstate/state_test.go:470 +0x71
testing.tRunner(0xc00042cf00, 0xc000473610)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1238 +0x2b3
FAIL	github.com/hashicorp/terraform/internal/command/jsonstate	0.262s
FAIL
```

Merging in the work from your branch on `mildwonkey/marked-panic` allows the test case to pass. I've also tested your fix running both `terraform show -json` and `terraform show -json plan.cache` on two of the environments where I experienced the crash, and it's resolved in both cases with your fix.

Feel free to cherry-pick the test case as you see fit https://github.com/davidalger/terraform/commit/8a9be61f808b6504c32e30cd6c5d97cec7bc5c78 but I think your fix on #29049 is correct.

**Comment by mildwonkey** [comment]
HA IT WAS MAPS I THOUGHT SO!!!
@davidalger thank you so much, you're awesome 😁 
Even though @apparentlymart fixed the root issue upstream, I think my PR is still valid (deleting redundant code is _always_ valid) so I'll cherry-pick that over to my PR. 

really truly appreciated, i was definitely hitting a wall and getting rather frustrated 😁 😂 😁

**Comment by mildwonkey** [comment]
This will be fixed in the next release, thanks everyone!

**Comment by rymnc** [comment]
@mildwonkey I'm still facing this issue with terraform cloud. When's the next release?
