### ISSUE TITLE
GCS backend does not work with GCP identity federation

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform#29656]
Related ticket: https://github.com/google-github-actions/auth/issues/17

The `auth` GitHub Action from Google allows us to federate identity to a GCP service account without having to export account credentials. Currently this does not work with the terraform GCS backend. Raw `gcloud` works fine.

### Terraform Version

```
 1.0.7
Go runtime version: go1.16.4
```

### Terraform Configuration Files

```terraform
terraform {
  backend "gcs" {
    bucket = "foo"
  }
}
```

### Expected Behavior

Terraform GCS backend working as usual.

### Actual Behavior

```
Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/xxx-terraform-state/o?alt=json&delimiter=%2F&pageToken=&prefix=terraform%2Fstate%2F&prettyPrint=false&projection=full&versions=false": oauth2/google: unable to generate access token: Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/terraform@xxx.iam.gserviceaccount.com:generateAccessToken": oauth2/google: status code 400: {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

### Steps to Reproduce

Create a GitHub Action:

```yaml
jobs:
  test:
    permissions:
      contents: read
      id-token: 'write'
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      with:
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
    -
      name: Terraform Init
      run: terraform init
```

**Comment by sethvargo** [comment]
I think you just need to update to the latest cloud storage SDK and it'll work.

**Comment by jketcham** [comment]
Looks like `cloud.google.com/go/storage` is currently set to [v1.10.0](https://github.com/googleapis/google-cloud-go/releases/tag/storage%2Fv1.10.0) [here](https://github.com/hashicorp/terraform/blob/2c8edfb2593a0c3cec044c1504bf1c1edd3f4a94/go.mod#L4), and the latest version available is [v1.18.2](https://github.com/googleapis/google-cloud-go/releases/tag/storage%2Fv1.18.2).

I'm running into an error with using google cloud storage as my state backend, where I get this error when using Workload Identity Federation for authentication:
```
Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: unknown credential type: "external_account"
```

Would love to see this resolved. I'd be glad to provide additional info beyond what I shared in [this issue](https://github.com/google-github-actions/auth/issues/89) to help.

**Comment by zotrix** [comment]
I rebuilt the teraform with the new gcs version (v1.18.2) and the plan was successful.

```
diff --git a/go.mod b/go.mod
index 6fdcccac0..b074ab18a 100644
--- a/go.mod
+++ b/go.mod
@@ -1,7 +1,7 @@
 module github.com/hashicorp/terraform
 
 require (
-	cloud.google.com/go/storage v1.10.0
+	cloud.google.com/go/storage v1.18.2
 	github.com/Azure/azure-sdk-for-go v45.0.0+incompatible
 	github.com/Azure/go-autorest/autorest v0.11.3
 	github.com/Azure/go-ntlmssp v0.0.0-20200615164410-66371956d46c // indirect
@@ -34,9 +34,9 @@ require (
 	github.com/dylanmei/winrmtest v0.0.0-20190225150635-99b7fe2fddf1
 	github.com/go-test/deep v1.0.3
 	github.com/gofrs/uuid v3.3.0+incompatible // indirect
-	github.com/golang/mock v1.4.4
-	github.com/golang/protobuf v1.4.2
-	github.com/google/go-cmp v0.5.2
+	github.com/golang/mock v1.6.0
+	github.com/golang/protobuf v1.5.2
+	github.com/google/go-cmp v0.5.6
 	github.com/google/uuid v1.1.1
 	github.com/gophercloud/gophercloud v0.10.1-0.20200424014253-c3bfe50899e5
 	github.com/gophercloud/utils v0.0.0-20200423144003-7c72efc7435d
@@ -122,14 +122,14 @@ require (
 	go.uber.org/multierr v1.1.0 // indirect
 	go.uber.org/zap v1.9.1 // indirect
 	golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
-	golang.org/x/mod v0.3.0
-	golang.org/x/net v0.0.0-20201110031124-69a78807bb2b
-	golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43
-	golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f
-	golang.org/x/text v0.3.5
-	golang.org/x/tools v0.0.0-20201028111035-eafbe7b904eb
-	google.golang.org/api v0.34.0
-	google.golang.org/grpc v1.31.1
+	golang.org/x/mod v0.4.2
+	golang.org/x/net v0.0.0-20210503060351-7fd8e65b6420
+	golang.org/x/oauth2 v0.0.0-20211005180243-6b3c2da341f1
+	golang.org/x/sys v0.0.0-20210917161153-d61c044b1678
+	golang.org/x/text v0.3.6
+	golang.org/x/tools v0.1.5
+	google.golang.org/api v0.58.0
+	google.golang.org/grpc v1.40.0
 	gopkg.in/ini.v1 v1.42.0 // indirect
 	gopkg.in/yaml.v2 v2.2.8
 	k8s.io/api v0.0.0-20190620084959-7cf5895f2711
@@ -142,4 +142,4 @@ replace k8s.io/client-go => k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
 
 go 1.14
 
-replace google.golang.org/grpc v1.31.1 => google.golang.org/grpc v1.27.1
+replace google.golang.org/grpc => google.golang.org/grpc v1.27.1
```

+ go mod tidy to update sums

**Comment by hkobayash** [comment]
It looks like it is already fix https://github.com/hashicorp/terraform/pull/28296 .

**Comment by uportalis** [comment]
Are you sure this is resolved?

Here is how I created the Google Cloud resources:
```bash

gcloud iam workload-identity-pools create "my-pool" \
  --project="${PROJECT_ID}" \
  --location="global" \
  --display-name="Demo pool"


gcloud iam workload-identity-pools providers create-oidc "my-provider" \
  --project="${PROJECT_ID}" \
  --location="global" \
  --workload-identity-pool="my-pool" \
  --display-name="Demo provider" \
  --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" \
  --issuer-uri="https://token.actions.githubusercontent.com"


gcloud iam service-accounts add-iam-policy-binding "sb-github-actions@${PROJECT_ID}.iam.gserviceaccount.com" \
  --project="${PROJECT_ID}" \
  --role="roles/iam.workloadIdentityUser" \
  --member="principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/my-pool/attribute.repository/mycompany/myrepo"

```

(I even tried with `principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/my-pool/*`.)

Here is my workflow:
```yaml
jobs:
  terraform:
    permissions:
      id-token: write
      contents: read
    runs-on: [self-hosted, linux, x64, on-prem, terraform]
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{secrets.IDENTITY_PROVIDER_ID}}'
          service_account: '${{secrets.SA_EMAIL}}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Terraform init
        run: |
          terraform init -input=false
```

Here is my backend:
```yaml
terraform {
  backend "gcs" {
    bucket = "myuniqueidentifier"
    prefix = "terraform/state/something"
  }
}
```

Here is my provider config:
```yaml
terraform {
  required_version = "1.1.6"
  required_providers {
    google      = {
      source  = "hashicorp/google"
      version = "~> 3.90"
    }
  }
}

provider "google" {
  region = var.region
  zone   = var.zone
}
```

I double-checked and retried several times from scratch following documentation at https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions   and at  https://cloud.google.com/iam/docs/using-workload-identity-federation#generate-automatic.

I tested granting my service account roles Storage Object Admin, then Storage Admin, then Owner, on the project that contains the bucket (which is not same project as the one containing the service account).

And I'm still getting the following error :

```
│ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/myuniqueidentifier/o?alt=json&delimiter=%2F&pageToken=&prefix=terraform%2Fstate%2Fsomething%2F&prettyPrint=false&projection=full&versions=false": impersonate: unable to generate access token: Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/***:generateAccessToken": oauth2/google: status code 403: {
│   "error": {
│     "code": 403,
│     "message": "The caller does not have permission",
│     "status": "PERMISSION_DENIED"
│   }
│ }
```

Any idea what I am doing wrong?

**Comment by crw** [comment]
Hi @uportalis, you may not get an answer in this thread if it is not an expansion of the original issue (which it may be!) Just in case, you can also try getting help from [the community forums](https://discuss.hashicorp.com/c/terraform-core/27), there are more people there to help with these types of questions. Thanks!

**Comment by NathanielRose** [comment]
This error also occurs if your pool is disabled. Please check for this.

**Comment by uportalis** [comment]
I don't know why it works when I grant the Workload Identity User role using `attribute.actore/uportalis`, but not when I use `attribute.repository/mycompany/myrepo`.
So, my problem is NOT related to this issue.

**Comment by aanjansai1112** [comment]
@uportalis attribute.actore/uportalis is your github user name ?

**Comment by uportalis** [comment]
@aanjansai1112  yes it is. I resolved my problem, which was NOT related to this issue.
I think the problem was that during my tests, the attribute mappings contained not only attibute.repository, but also attribute.actor. It works fine now.

**Comment by Madapati460** [comment]
@uportalis could you please elaborate on the solution how it got fixed now ? are you suggesting to remove attribute.actor or any other method that you have followed.

**Comment by SarahFrench** [comment]
Based on [this comment](https://github.com/hashicorp/terraform/issues/29656#issuecomment-996429472), I believe this issue was addressed by https://github.com/hashicorp/terraform/pull/32203.

I'll close this issue soon if I don't hear anyone reporting it as not resolved.

**Comment by m13v** [comment]
we use Workload Identity Federation for our GitHub Actions deploys to Cloud Run and it's been solid. the setup is a bit involved (create a WIF pool, connect the GitHub OIDC provider, grant roles to the principal set) but once it works you never deal with JSON key files again. for the GCS backend specifically, the main blocker we hit was that the terraform init step needs the WIF credentials available before any providers load.

**Comment by m13v** [comment]
our Workload Identity Federation setup for GitHub Actions to Cloud Run: https://github.com/m13v/fazm - the deploy workflow in .github/workflows/ uses WIF with no stored keys.

**Comment by SarahFrench** [comment]
I decided to spend the time to manually test this - the gcs backend can use the outputs from google-github-actions/auth@v2 fine, via ADC.
