### ISSUE TITLE
TRACE level logging when TF_LOG=DEBUG

### ISSUE THREAD

**Issue by buzztroll** [hashicorp/terraform#6468]
When I run terraform with the environment variable TF_LOG=DEBUG I see TRACE level messages in the log.
### Terraform Version

Terraform v0.6.16-dev (9827bfe1a37234be766a7d9a822f559c09ec1f35)
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `export TF_LOG=DEBUG`
2. `export TF_TF_LOG_PATH=/tmp/log`
3. `terraform apply`
4. observe TRACE level logs in the file /tmp/log

**Comment by chadgrant** [comment]
I'm using TF_LOG=ERROR and seeing WARN,DEBUG,TRACE messages. filter doesn't seem applied at all

**Comment by bigkraig** [comment]
totally broken, setting TF_LOG to anything results in all logs

**Comment by bsomogyi** [comment]
Seeing the same problem on 0.7.5   TF_LOG=ERROR does not reduce verbosity, it produces more logs than if TF_LOG was not set.

**Comment by carmat88** [comment]
Hello Folks! To date my colleagues and I have encountered the same issue, however our scenario it is slightly different. In fact it seems that with the latest version of terraform this bug have been addressed. In our case though we are building an image with packer and during its post-processor the `terraform build` command is run in order to spawn a machine and run a script (due to Travis CI performance limitation, hence we need to spawn a more powerful machine for taking care of certain steps of the image building).

Unfortunately no matter how we tweak the env variable `TF_LOG` and `PACKER_LOG`, very verbose logs are returned [because `TRACE` value is taken as default], making the debugging process tedious when errors occur. To not mention that Travis CI can fail when even the raw log is too long. Here is the link to our Travis log:

https://travis-ci.org/kubenow/image/jobs/247036835

On the other hand, in a different build, when a terraform command is directly executed within Travis CI environment [instead of being run from within packer] then no need to tweak the `TF_LOG` variable as a simpler log is returned. Here it is an example:

https://travis-ci.org/kubenow/KubeNow/jobs/251509221

Would you have any insights on how to address this issue or any news in general about the above mention bug? Please let us know. Cheers!

**Comment by apparentlymart** [comment]
Hi all. Sorry for the weirdness here.

We believe that the problem here results from the fact that most logging comes from providers and that logs from providers get prefixed with the provider name, thus preventing them from being recognized as having a log level. This is something we'd like to fix eventually, but we're not working on it immediately due to other issues to address. I can understand the frustration it causes though, since often the log output is currently the only place where certain debug information is included.

**Comment by carmat88** [comment]
Hey @apparentlymart . Many thanks for getting back and for the details. Cheers.

**Comment by fgimian** [comment]
Just wanted to mention that this still occurs on the latest Terraform version.

**Comment by nreisb** [comment]
Still occurring in Terraform v0.11.1 as well.

**Comment by domdom82** [comment]
I feel trying to read the log level from the log string instead of a proper `logLevel` argument is the original root cause here...

**Comment by endzyme** [comment]
still happening on v0.11.2

**Comment by apparentlymart** [comment]
The Terraform team as HashiCorp is not working on this issue at this time due to other priorities. We'll update here when there's more news.

**Comment by twglomski** [comment]
I'd like this fixed to better integrate Terraform with our log aggregation solution - as it currently is it'd flood my log system with garbage. Thanks and hope you're able to prioritize this soon!

**Comment by sheerun** [comment]
i think this is fixed on master maybe @twglomski can double check

**Comment by sheerun** [comment]
It seems that logs from provider are truncated though

**Comment by fisica3** [comment]
Any idea of when this could be solved? The provider log (AWS) is verbosy and it shows sensitive data now that we are using the recent aws_secretsmanager_secret.

**Comment by kallon** [comment]
Yep.  please fix

**Comment by tony-kerz** [comment]
`v0.11.7`

**Comment by apparentlymart** [comment]
Leaving "yes please" comments doesn't help because we can't report on those, so it just creates noise for those already following the issue. To influence prioritization, please leave a :+1: reaction on the opening comment of this issue, which [we can report on](https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) and use as an input when planning work for future releases.

**Comment by phosphre** [comment]
@apparentlymart, is it possible that recent (a la azurerm 1.30.x) providers which are now 0.12 compliant might be producing different or increased amount of logging?

And is it possible that with big graphs (like mine), the IO to the TTY (speculative TFE plan) might be slowing down the operation - I'm thinking my graph which was already close to the 60 min provider timeout might now be big enough that, with the additional logging (even with TF_LOG= set), the slowdown with all the `<blah>  - *terraform.NodeRootVariable` lines pushes the time over the timeout?

**Comment by phosphre** [comment]
Also, if I set
`TF_LOG=`
I then get
2019/07/18 15:54:44 [DEBUG] Using modified User-Agent: Terraform/0.11.14 PTFE/ecddff1
but this output line surely is core?

**Comment by hmalphettes** [comment]
@phosphre this particular log statement comes from https://github.com/hashicorp/terraform/blob/98a796c3a30b31c71dd7c834cff75c975e487718/httpclient/useragent.go#L24 (this is the current master as of today)

```
log.Printf("[DEBUG] Using modified User-Agent: %s", ua)
```

Terraform core is using in a number of places the "log" package of golang.
As far as I know there is no way to filter them by level with the current CLI options.

@apparentlymart if you want me to take a stab at replacing the uses of "log" by "go-hclog" or another package of your choice, let me know.

**Comment by bukzor** [comment]
I'm in the same boat as @phosphre -- the fact that I can't turn off these logs is slowing us down by many minutes. Terraform is wasting time writing hundreds Megabytes of TRACE level details to disk before it does anything useful.

**Comment by ml4** [comment]
@bukzor if possible, please retry this with v0.12.18 and let us know if the problem still occurs.

**Comment by bukzor** [comment]
That's a big project for us that's currently underway. I'll report back when we're off v0.11.

**Comment by andrey-ciandt** [comment]
I'm running on this issue on terraform v0.12.11.
There is an official release with it fixed? Asking because I see the issue still open here

**Comment by jbardin** [comment]
This is fixed  in master.
Core is now using `hclog` throughout, allowing for better control over the logging subsystems.
Some plugins will need to be updated to present the expected log levels to core in certain cases, but they will still be filtered correctly in the CLI.

Closed by #26632, #26665, #26685 and #26694
