### ISSUE TITLE
unexpected cycles when using count=

### ISSUE THREAD

**Issue by justin8** [hashicorp/terraform#7741]
### Terraform Version

Terraform v0.6.16
### Affected Resource(s)
- aws_efs_mount_target
- aws_subnet
### Terraform Configuration Files

https://www.dropbox.com/s/jljcct68i6luiwc/configuration-files.tar.gz?dl=0
### Debug Output

Doesn't get far enough to have debug output
### Expected Behavior

What should have happened?
There shouldn't be a dependency loop between the efs mount and subnets when multiple mounts are defined using count
### Actual Behavior

What actually happened?
There is a dependency loop between efs mounts and subnets when multiple mounts are defined using count
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `cd ci`
2. `terraform plan`
### Important Factoids

If the `aws_efs_mount_target` in `efs/main.tf` is replaced by 2 entries, with `count` undefined and with `subnet_id = "${element(split(",",var.subnets),0)}"` and `subnet_id = "${element(split(",",var.subnets),1)}"` (which is all that should be changing when `count` is specified) then it will work as expected. I only see this dependency cycle when generating resources using count

**Comment by morea-deploy-alloresto** [comment]
Same bug with Terraform v0.7.0

**Comment by GuillaumK** [comment]
Same bug with Terraform v0.7.0

**Comment by brentley** [comment]
I'm fighting this also.

**Comment by pbthorste** [comment]
+1

**Comment by jjohnson1024** [comment]
+1

**Comment by jjohnson1024** [comment]
Actually, I +1'd this as its almost exactly what I'm running into, but then I found this issue:

https://github.com/hashicorp/terraform/issues/7741

This also matches my situation.

**Comment by notjames** [comment]
```
 65 resource "aws_efs_mount_target" "proj-efs"
 66 {
 67   count          = "${length(aws_subnet.private.*.id)}"
 68   file_system_id = "${aws_efs_file_system.proj-efs.id}"
 69   subnet_id      = "${element(aws_subnet.private.*.id, count.index)}"
 70 }
```

```
Error loading Terraform: module private-subnets.vpc.root: 1 error(s) occurred:

* aws_efs_mount_target.proj-efs: resource count can't reference resource variable: aws_subnet.private.*.id
```

Please fix ASAP. Seems like `count` is not being used as a top-level resource for this resource.

**Comment by apparentlymart** [comment]
Hi @justin8, and everyone else who has commented here! Sorry for this issue, and sorry we let it languish here for so long.

Unfortunately I left this so long before looking at it that the original configuration example is now a dead link, so I can't be sure but I have a suspicion that this is really the same root issue as #2301, which is now resolved. (but see my comment there for the caveat in its resolution)

Thus I'm going to tentatively close this one out as well. If anyone is still seeing similar symptoms on the latest version I'd encourage you to open a fresh issue so we can triage and address it separately, since the relevant parts of Terraform have changed quite drastically since 0.6.16.

---

@notjames your issue there seems to be something different: Terraform is failing because you referenced `aws_subnet.private.*.id` in `count`, which in 0.8.8 isn't permitted because you can't use resource attributes in `count`. As of 0.9 it's possible to use non-computed resource attributes in `count`, so while I think you still won't be able to write exactly what you wrote there you should be able to express the same idea like this:

```hcl
  count = "${aws_subnet.private.count}"
```

(Taking the length of the "splat variable" won't work here because the splat variable is marked as *computed* until all of the resources have been created, and applying any function to a computed value always produces a computed result. But Terraform knows the `count` of that block, so if you can avoid introducing computed values and thus get the intended result.)

**Comment by notjames** [comment]
@apparentlymart thanks for the info. So, I'm just trying to create EFS volumes and their associated mount_targets; one per AZ. So, the following code is used to create the volume:

```
 49 resource "aws_efs_file_system" "data"
 50 {
 51   creation_token   = "data"
 52   performance_mode = "generalPurpose"
 53
 54 #  lifecycle
 55 #  {
 56 #    prevent_destroy= "true"
 57 #  }
 58
 59   tags
 60   {
 61     "Name" = "${var.project-name}-${var.environment}-efs"
 62   }
 63 }
```

and the associated mount target HCL that I was trying to do:

```
 72 resource "aws_efs_mount_target" "data"
 73 {
 74   count          = "${aws_subnet.private.count}"  # doesn't work
 75   file_system_id = "${aws_efs_file_system.car_data.id}"
 76   subnet_id      = "${element(aws_subnet.private.*.id, count.index)}"
 77 }
```

If this can't get working then I have to manually specify the mount_target for each AZ that I want EFS to peer in.

**Comment by cirocosta** [comment]
Hey @notjames, how did you end up working around it?

**Comment by mingfang** [comment]
I'm still getting ```aws_efs_mount_target.target: value of 'count' cannot be computed`` problem in v0.10.5. with this code ```count  = "${length(var.subnet_ids)}"```

why is this issue closed?
