### ISSUE TITLE
"Unexpected EOF" and "connection is shut down" with google providers when using terraform 0.7.1

### ISSUE THREAD

**Issue by sbadia** [hashicorp/terraform#8341]
Hi there,

I just switched to `terraform 0.7.1`, my infra is a mix of `±200` ressources on gcp + openstack (so multi provider).

**Note**: Everything work's like a charm with `terraform 0.7.0`

### Terraform Version
* `terraform 0.7.1`

### Affected Resource(s)

- `google_*`

### Debug Output

* http://pub.sebian.fr/pub/crash-run.log.gpg
 * `size:8417`
 * `hash:b56ac0776faa3f638bf919ba130509fb`
 * crypted with `0x51852D87348FFC4C`

### Panic Output

* http://pub.sebian.fr/pub/crash.log.gpg
 * `size:279154`
 * `hash:90280650f20ba041310e84f247cc1b9a`
 * crypted with `0x51852D87348FFC4C`

### Expected Behavior

> What should have happened?

Terraform should report or execute the plan for `google_records`

### Actual Behavior

> What actually happened?

Any `google_record` throws either a "Unexpected EOF" and "connection is shut down" error.

**Note**: I tried with `-parallelism=1` as suggested in https://github.com/hashicorp/terraform/issues/8011#issuecomment-238953349 but no change…

### Steps to Reproduce
1. `terraform plan`

### Important Factoids

> Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

No

### References
Maybe this one (but for cloudfare ressources)
- GH-8011

Thanks in advance!

**Comment by vaygr** [comment]
Same issue here.

**Comment by jaygorrell** [comment]
Same here from Atlas with AWS.  Worked great on 0.7.0.

**Comment by cblecker** [comment]
Hi @sbadia!
From what I can see "unexpected EOF" usually relates to an issue with your local system communicating with the provider's API. Also, what OS/arch are you running on your local system (`uname -a`)?

@vaygr reported a similar issue in #8345, but I wasn't able to duplicate it using Mac OS X 10.11.6 (Darwin x86_64). I can't see your debugs as they're encrypted and I'm not a member of the terraform team, but perhaps you can compare them to @vaygr's to see if they are similar.

**Comment by jen20** [comment]
Looks like this is potentially related to #8345, we'll try to ensure this is fixed and released in 0.7.2.

**Comment by sbadia** [comment]
hi, sorry for the delay!

@cblecker I use Debian GNU/Linux with a 4.6.0 kernel 
`Linux baloo 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux` 

the panic error seems indeed related `panic: interface conversion: interface is nil, not string`

Just re-tested with master `Terraform v0.7.2-dev (a69c62af655184bbb164f3516929c830862c57ed)` I still have the issue with a `plan` :-/ 

* [crash.log terraform v0.7.2-dev](https://gist.githubusercontent.com/sbadia/6988ac5b9b28abb2ebd6b89e3c9b9a7a/raw/6e22bedca98b8a87e727285b345f342b16c40f16/hashicorp%2520terraform%2520%25238341)

**Comment by rvrignaud** [comment]
Same issue described above on same terraform files have been reproduced on OS X 10.11

**Comment by sbadia** [comment]
The PR #8390 solve this issue. Thanks @jen20 !

```
❯ curl -s https://patch-diff.githubusercontent.com/raw/hashicorp/terraform/pull/8390.patch | git apply -
❯ make
[…]
❯ XC_OS=linux XC_ARCH=amd64 make bin
[…]
❯ terraform version
Terraform v0.7.2-dev (51d669be44a696c868faa8719253859fac312d4a+CHANGES)
```
Everything re-work fine :)
