### ISSUE TITLE
Terraform fails to apply config on existing ALB Target Groups

### ISSUE THREAD

**Issue by nicolas-g** [hashicorp/terraform#9154]
We are using a module in order to create new AWS Application Load Balancers (ALB) along with the desired security groups, listeners and target groups.

When the Target Group name is change in our config Terraform apply shows that runs successful but it hasn't actually made any changes on the target group, each time you run plan you see the target group should be renamed.

The main reason for that is because the target groups cannot be renamed and need to be re-created with the new name, I think Terraform tries to terminate the existing Target Group in order to create a new one but it can't because in order to delete a Target Group it must not be used by any LB listener.

The manually solution we follow is to manually go to the AWS console and , remove that target group from any LB listener and delete the target group my self, then Terraform apply will run successfully and running plan later will show no differences.

This is an annoying and time consuming procedure, I would expect Terraform can handle and automate all that.

### Terraform Version
Terraform v0.7.3

### Affected Resource(s)
- aws_alb_target_group

### Terraform Configuration Files
```
# Create a HTTPS target group
resource "aws_alb_target_group" "service_public_443" {
  name     = "${var.service_prefix}-${var.env}-public-443"
  port     = 443
  protocol = "HTTPS"
  vpc_id   = "${data.terraform_remote_state.network.vpc-id}"

  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 5
    interval            = 30
    path                = "${var.health_check_path}"
    protocol            = "HTTPS"
    port                = 443
  }
}
```

### Expected Behavior
Terrafrom should be able to have renamed or re-provision the target group.

### Actual Behavior
It doesn't matter how many times I run plan and apply , apply will show success but plan will show the bellow : 
```
~ module.service.aws_alb_target_group.service_public_443
    name: "name-prod-443" => "newname-prod-public-443"
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`
3. repeat #1 and #2 as many times..

**Comment by stack72** [comment]
Hi @nicolas-g 

Thanks for the bug report here - luckily, we have already fixed this for Terraform 0.7.5 via #8989

This should be released with the next couple of days

Thanks

Paul

**Comment by gustavosoares** [comment]
Has this been fixed? I am having the same issue now.. running terraform v0.8.8

**Comment by mperriere** [comment]
Hello,
same issue actually with 0.8.6.

**Comment by marccardinal** [comment]
This is indeed still occurring in v0.8.8, I have to rename the target_group when I make changes.

**Comment by stack72** [comment]
Hi @marccardinal / @gustavosoares 

Please can you help me understand what issue you are facing?

Paul

**Comment by gustavosoares** [comment]
Sorry for the late reply @stack72  (easter holiday). I've created a target group with terraform, then I made some changes and terraform failed to apply it.
